/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package deu.view;

import deu.controller.ui.HomeSwingController;
import lombok.Getter;
import lombok.Setter;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

/**
 *
 * @author oxxultus
 */
@Getter
@Setter
public class Auth extends javax.swing.JFrame {

    /**
     * Creates new form Auth
     */
    public Auth() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        login = new javax.swing.JPanel();
        login_loginNumberField = new deu.view.custom.TextFieldRound();
        login_loginPasswordField = new deu.view.custom.PasswordFieldRound();
        login_loginButton = new deu.view.custom.ButtonRound();
        login_signupButton = new deu.view.custom.ButtonRound();
        login_forgotPassword = new javax.swing.JLabel();
        login_loginNumberLabel = new javax.swing.JLabel();
        login_loginPasswordLabel = new javax.swing.JLabel();
        login_loginTitle = new javax.swing.JLabel();
        login_loginDescription = new javax.swing.JLabel();
        login_loginLogo = new javax.swing.JLabel();
        login_deuProjectLogo = new javax.swing.JLabel();
        login_deuProjectTitle = new javax.swing.JLabel();
        login_team1 = new javax.swing.JLabel();
        login_name1 = new javax.swing.JLabel();
        login_team2 = new javax.swing.JLabel();
        login_name2 = new javax.swing.JLabel();
        login_name3 = new javax.swing.JLabel();
        login_name4 = new javax.swing.JLabel();
        login_name5 = new javax.swing.JLabel();
        login_deuProjectDescription1 = new javax.swing.JLabel();
        login_deuProjectDescription2 = new javax.swing.JLabel();
        login_githubLogo = new javax.swing.JLabel();
        login_githubLogoTitle = new javax.swing.JLabel();
        login_githubButton = new deu.view.custom.ButtonRound();
        login_SideBarLabel = new deu.view.custom.LabelRound();
        signup = new javax.swing.JPanel();
        signup_signupNumberField = new deu.view.custom.TextFieldRound();
        signup_undoButton = new deu.view.custom.ButtonRound();
        signup_signupButton = new deu.view.custom.ButtonRound();
        signup_signupPasswordField = new deu.view.custom.TextFieldRound();
        signup_signupNameField = new deu.view.custom.TextFieldRound();
        signup_signupMajorField = new deu.view.custom.TextFieldRound();
        signup_signupPasswordLabel = new javax.swing.JLabel();
        signup_signupNameLabel = new javax.swing.JLabel();
        signup_signupMajorLabel = new javax.swing.JLabel();
        signup_loginNumberLabel = new javax.swing.JLabel();
        signup_signupTitle = new javax.swing.JLabel();
        signup_signupDescription = new javax.swing.JLabel();
        signup_loginLogo = new javax.swing.JLabel();
        signup_deuProjectLogo = new javax.swing.JLabel();
        signup_deuProjectTitle = new javax.swing.JLabel();
        signup_team1 = new javax.swing.JLabel();
        signup_name1 = new javax.swing.JLabel();
        signup_team2 = new javax.swing.JLabel();
        signup_name2 = new javax.swing.JLabel();
        signup_name3 = new javax.swing.JLabel();
        signup_name4 = new javax.swing.JLabel();
        signup_name5 = new javax.swing.JLabel();
        signup_deuProjectDescription1 = new javax.swing.JLabel();
        signup_deuProjectDescription2 = new javax.swing.JLabel();
        signup_githubLogo = new javax.swing.JLabel();
        signup_githubLogoTitle = new javax.swing.JLabel();
        signup_githubButton = new deu.view.custom.ButtonRound();
        signup_signupSideBarLabel = new deu.view.custom.LabelRound();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("강의실 예약 프로그램");
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setPreferredSize(new java.awt.Dimension(1100, 630));
        setResizable(false);
        setSize(new java.awt.Dimension(1100, 630));
        getContentPane().setLayout(new java.awt.CardLayout());

        login.setBackground(new java.awt.Color(255, 255, 255));
        login.setForeground(new java.awt.Color(255, 255, 255));
        login.setToolTipText("");
        login.setMaximumSize(new java.awt.Dimension(1100, 600));
        login.setMinimumSize(new java.awt.Dimension(1100, 600));
        login.setSize(new java.awt.Dimension(1100, 600));
        login.setLayout(null);

        login_loginNumberField.setBackground(new java.awt.Color(255, 255, 255));
        login_loginNumberField.setCaretColor(new java.awt.Color(0, 0, 0));
        login_loginNumberField.setNormalTextColor(java.awt.Color.black);
        login_loginNumberField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        login.add(login_loginNumberField);
        login_loginNumberField.setBounds(460, 290, 460, 40);

        login_loginPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        login_loginPasswordField.setCaretColor(new java.awt.Color(0, 0, 0));
        login_loginPasswordField.setNormalTextColor(java.awt.Color.black);
        login_loginPasswordField.setRound(15);
        login_loginPasswordField.setSelectedTextColor(new java.awt.Color(0, 0, 0));
        login.add(login_loginPasswordField);
        login_loginPasswordField.setBounds(460, 370, 460, 40);

        login_loginButton.setBackground(new java.awt.Color(20, 90, 170));
        login_loginButton.setForeground(new java.awt.Color(255, 255, 255));
        login_loginButton.setText("로그인");
        login_loginButton.setBorderColor(new java.awt.Color(13, 13, 13));
        login_loginButton.setRoundBottomLeft(15);
        login_loginButton.setRoundBottomRight(15);
        login_loginButton.setRoundTopLeft(15);
        login_loginButton.setRoundTopRight(15);
        login.add(login_loginButton);
        login_loginButton.setBounds(460, 450, 460, 40);

        login_signupButton.setBackground(new java.awt.Color(20, 90, 170));
        login_signupButton.setForeground(new java.awt.Color(255, 255, 255));
        login_signupButton.setText("회원가입");
        login_signupButton.setBorderColor(new java.awt.Color(13, 13, 13));
        login_signupButton.setRoundBottomLeft(15);
        login_signupButton.setRoundBottomRight(15);
        login_signupButton.setRoundTopLeft(15);
        login_signupButton.setRoundTopRight(15);
        login.add(login_signupButton);
        login_signupButton.setBounds(460, 500, 460, 40);

        login_forgotPassword.setForeground(new java.awt.Color(51, 153, 255));
        login_forgotPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        login_forgotPassword.setText("forgot password");
        login.add(login_forgotPassword);
        login_forgotPassword.setBounds(750, 420, 170, 18);

        login_loginNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        login_loginNumberLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_loginNumberLabel.setForeground(new java.awt.Color(153, 153, 153));
        login_loginNumberLabel.setText("Student Number or Professor Number or Manager Number");
        login.add(login_loginNumberLabel);
        login_loginNumberLabel.setBounds(460, 270, 380, 18);

        login_loginPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        login_loginPasswordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        login_loginPasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        login_loginPasswordLabel.setText("Password");
        login.add(login_loginPasswordLabel);
        login_loginPasswordLabel.setBounds(460, 350, 170, 18);

        login_loginTitle.setBackground(new java.awt.Color(5, 5, 5));
        login_loginTitle.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        login_loginTitle.setForeground(new java.awt.Color(5, 5, 5));
        login_loginTitle.setText("Login");
        login.add(login_loginTitle);
        login_loginTitle.setBounds(650, 160, 67, 40);

        login_loginDescription.setForeground(new java.awt.Color(153, 153, 153));
        login_loginDescription.setText("Login into your account LectureRoomReservationSystem");
        login.add(login_loginDescription);
        login_loginDescription.setBounds(520, 210, 330, 17);

        login_loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/sign-in.png"))); // NOI18N
        login.add(login_loginLogo);
        login_loginLogo.setBounds(660, 100, 50, 40);

        login_deuProjectLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/git-repository.png"))); // NOI18N
        login.add(login_deuProjectLogo);
        login_deuProjectLogo.setBounds(30, 30, 30, 30);

        login_deuProjectTitle.setBackground(new java.awt.Color(204, 204, 204));
        login_deuProjectTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        login_deuProjectTitle.setForeground(new java.awt.Color(102, 102, 102));
        login_deuProjectTitle.setText("DEU Project");
        login.add(login_deuProjectTitle);
        login_deuProjectTitle.setBounds(70, 35, 160, 20);

        login_team1.setBackground(new java.awt.Color(255, 255, 255));
        login_team1.setForeground(new java.awt.Color(102, 102, 102));
        login_team1.setText("팀장");
        login.add(login_team1);
        login_team1.setBounds(30, 110, 22, 17);

        login_name1.setBackground(new java.awt.Color(255, 255, 255));
        login_name1.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        login_name1.setForeground(new java.awt.Color(102, 102, 102));
        login_name1.setText("강준화 - 파트");
        login.add(login_name1);
        login_name1.setBounds(50, 130, 210, 23);

        login_team2.setBackground(new java.awt.Color(255, 255, 255));
        login_team2.setForeground(new java.awt.Color(102, 102, 102));
        login_team2.setText("팀원");
        login.add(login_team2);
        login_team2.setBounds(30, 160, 22, 17);

        login_name2.setBackground(new java.awt.Color(255, 255, 255));
        login_name2.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        login_name2.setForeground(new java.awt.Color(102, 102, 102));
        login_name2.setText("김영진 - 파트");
        login.add(login_name2);
        login_name2.setBounds(50, 180, 210, 23);

        login_name3.setBackground(new java.awt.Color(255, 255, 255));
        login_name3.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        login_name3.setForeground(new java.awt.Color(102, 102, 102));
        login_name3.setText("김원형 - 파트");
        login.add(login_name3);
        login_name3.setBounds(50, 220, 210, 23);

        login_name4.setBackground(new java.awt.Color(255, 255, 255));
        login_name4.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        login_name4.setForeground(new java.awt.Color(102, 102, 102));
        login_name4.setText("이시연 - 파트");
        login.add(login_name4);
        login_name4.setBounds(50, 260, 210, 23);

        login_name5.setBackground(new java.awt.Color(255, 255, 255));
        login_name5.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        login_name5.setForeground(new java.awt.Color(102, 102, 102));
        login_name5.setText("이건일 - 파트");
        login.add(login_name5);
        login_name5.setBounds(50, 300, 210, 23);

        login_deuProjectDescription1.setBackground(new java.awt.Color(204, 204, 204));
        login_deuProjectDescription1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        login_deuProjectDescription1.setForeground(new java.awt.Color(102, 102, 102));
        login_deuProjectDescription1.setText("소프트웨어 공학 시간에 진행하는자바로 구현 한 ");
        login.add(login_deuProjectDescription1);
        login_deuProjectDescription1.setBounds(20, 460, 230, 20);

        login_deuProjectDescription2.setBackground(new java.awt.Color(204, 204, 204));
        login_deuProjectDescription2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        login_deuProjectDescription2.setForeground(new java.awt.Color(102, 102, 102));
        login_deuProjectDescription2.setText("빈 강의실 예약 프로그램 만들기 프로젝트 입니다.");
        login.add(login_deuProjectDescription2);
        login_deuProjectDescription2.setBounds(20, 480, 230, 20);

        login_githubLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/github.png"))); // NOI18N
        login.add(login_githubLogo);
        login_githubLogo.setBounds(23, 512, 50, 50);

        login_githubLogoTitle.setBackground(new java.awt.Color(255, 255, 255));
        login_githubLogoTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        login_githubLogoTitle.setForeground(new java.awt.Color(34, 37, 40));
        login_githubLogoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        login_githubLogoTitle.setText("LectureRoomReservationSystem");
        login.add(login_githubLogoTitle);
        login_githubLogoTitle.setBounds(80, 520, 170, 14);

        login_githubButton.setBackground(new java.awt.Color(204, 204, 204));
        login_githubButton.setForeground(new java.awt.Color(102, 102, 102));
        login_githubButton.setText("이동하기");
        login_githubButton.setToolTipText("");
        login_githubButton.setRoundBottomLeft(10);
        login_githubButton.setRoundBottomRight(10);
        login_githubButton.setRoundTopLeft(10);
        login_githubButton.setRoundTopRight(10);
        login.add(login_githubButton);
        login_githubButton.setBounds(80, 540, 170, 20);

        login_SideBarLabel.setBackground(new java.awt.Color(249, 249, 251));
        login_SideBarLabel.setForeground(new java.awt.Color(34, 37, 40));
        login.add(login_SideBarLabel);
        login_SideBarLabel.setBounds(0, 0, 270, 600);

        getContentPane().add(login, "login");

        signup.setBackground(new java.awt.Color(255, 255, 255));
        signup.setForeground(new java.awt.Color(255, 255, 255));
        signup.setToolTipText("");
        signup.setMaximumSize(new java.awt.Dimension(1100, 600));
        signup.setMinimumSize(new java.awt.Dimension(1100, 600));
        signup.setSize(new java.awt.Dimension(1100, 600));
        signup.setLayout(null);

        signup_signupNumberField.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupNumberField.setNormalTextColor(java.awt.Color.black);
        signup.add(signup_signupNumberField);
        signup_signupNumberField.setBounds(460, 250, 460, 40);

        signup_undoButton.setBackground(new java.awt.Color(204, 204, 204));
        signup_undoButton.setForeground(new java.awt.Color(0, 0, 0));
        signup_undoButton.setText("취소");
        signup_undoButton.setRoundBottomLeft(0);
        signup_undoButton.setRoundBottomRight(15);
        signup_undoButton.setRoundTopLeft(0);
        signup_undoButton.setRoundTopRight(15);
        signup.add(signup_undoButton);
        signup_undoButton.setBounds(830, 520, 90, 40);

        signup_signupButton.setBackground(new java.awt.Color(20, 90, 170));
        signup_signupButton.setForeground(new java.awt.Color(255, 255, 255));
        signup_signupButton.setText("회원가입");
        signup_signupButton.setRoundBottomLeft(15);
        signup_signupButton.setRoundBottomRight(0);
        signup_signupButton.setRoundTopLeft(15);
        signup_signupButton.setRoundTopRight(0);
        signup.add(signup_signupButton);
        signup_signupButton.setBounds(460, 520, 380, 40);

        signup_signupPasswordField.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupPasswordField.setNormalTextColor(java.awt.Color.black);
        signup.add(signup_signupPasswordField);
        signup_signupPasswordField.setBounds(460, 320, 460, 40);

        signup_signupNameField.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupNameField.setNormalTextColor(java.awt.Color.black);
        signup.add(signup_signupNameField);
        signup_signupNameField.setBounds(460, 390, 460, 40);

        signup_signupMajorField.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupMajorField.setNormalTextColor(java.awt.Color.black);
        signup.add(signup_signupMajorField);
        signup_signupMajorField.setBounds(460, 460, 460, 40);

        signup_signupPasswordLabel.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupPasswordLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        signup_signupPasswordLabel.setForeground(new java.awt.Color(153, 153, 153));
        signup_signupPasswordLabel.setText("Password");
        signup.add(signup_signupPasswordLabel);
        signup_signupPasswordLabel.setBounds(460, 300, 380, 18);

        signup_signupNameLabel.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupNameLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        signup_signupNameLabel.setForeground(new java.awt.Color(153, 153, 153));
        signup_signupNameLabel.setText("Full Name");
        signup.add(signup_signupNameLabel);
        signup_signupNameLabel.setBounds(460, 370, 380, 18);

        signup_signupMajorLabel.setBackground(new java.awt.Color(255, 255, 255));
        signup_signupMajorLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        signup_signupMajorLabel.setForeground(new java.awt.Color(153, 153, 153));
        signup_signupMajorLabel.setText("Major");
        signup.add(signup_signupMajorLabel);
        signup_signupMajorLabel.setBounds(460, 440, 380, 18);

        signup_loginNumberLabel.setBackground(new java.awt.Color(255, 255, 255));
        signup_loginNumberLabel.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        signup_loginNumberLabel.setForeground(new java.awt.Color(153, 153, 153));
        signup_loginNumberLabel.setText("Number");
        signup.add(signup_loginNumberLabel);
        signup_loginNumberLabel.setBounds(460, 230, 380, 18);

        signup_signupTitle.setBackground(new java.awt.Color(0, 0, 0));
        signup_signupTitle.setFont(new java.awt.Font("Helvetica", 1, 24)); // NOI18N
        signup_signupTitle.setForeground(new java.awt.Color(0, 0, 0));
        signup_signupTitle.setText("Signup");
        signup.add(signup_signupTitle);
        signup_signupTitle.setBounds(640, 160, 83, 40);

        signup_signupDescription.setForeground(new java.awt.Color(153, 153, 153));
        signup_signupDescription.setText("Please Sign-up before LectureRoom Reservation System");
        signup.add(signup_signupDescription);
        signup_signupDescription.setBounds(520, 210, 340, 17);

        signup_loginLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/sign-in.png"))); // NOI18N
        signup.add(signup_loginLogo);
        signup_loginLogo.setBounds(660, 100, 50, 40);

        signup_deuProjectLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/git-repository.png"))); // NOI18N
        signup.add(signup_deuProjectLogo);
        signup_deuProjectLogo.setBounds(30, 30, 30, 30);

        signup_deuProjectTitle.setBackground(new java.awt.Color(204, 204, 204));
        signup_deuProjectTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 18)); // NOI18N
        signup_deuProjectTitle.setForeground(new java.awt.Color(0, 0, 0));
        signup_deuProjectTitle.setText("DEU Project");
        signup.add(signup_deuProjectTitle);
        signup_deuProjectTitle.setBounds(70, 35, 160, 20);

        signup_team1.setBackground(new java.awt.Color(255, 255, 255));
        signup_team1.setForeground(new java.awt.Color(102, 102, 102));
        signup_team1.setText("팀장");
        signup.add(signup_team1);
        signup_team1.setBounds(30, 110, 22, 17);

        signup_name1.setBackground(new java.awt.Color(255, 255, 255));
        signup_name1.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        signup_name1.setForeground(new java.awt.Color(102, 102, 102));
        signup_name1.setText("강준화 - 파트");
        signup.add(signup_name1);
        signup_name1.setBounds(50, 130, 210, 23);

        signup_team2.setBackground(new java.awt.Color(255, 255, 255));
        signup_team2.setForeground(new java.awt.Color(102, 102, 102));
        signup_team2.setText("팀원");
        signup.add(signup_team2);
        signup_team2.setBounds(30, 160, 22, 17);

        signup_name2.setBackground(new java.awt.Color(255, 255, 255));
        signup_name2.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        signup_name2.setForeground(new java.awt.Color(102, 102, 102));
        signup_name2.setText("김영진 - 파트");
        signup.add(signup_name2);
        signup_name2.setBounds(50, 180, 210, 23);

        signup_name3.setBackground(new java.awt.Color(255, 255, 255));
        signup_name3.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        signup_name3.setForeground(new java.awt.Color(102, 102, 102));
        signup_name3.setText("김원형 - 파트");
        signup.add(signup_name3);
        signup_name3.setBounds(50, 220, 210, 23);

        signup_name4.setBackground(new java.awt.Color(255, 255, 255));
        signup_name4.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        signup_name4.setForeground(new java.awt.Color(102, 102, 102));
        signup_name4.setText("이시연 - 파트");
        signup.add(signup_name4);
        signup_name4.setBounds(50, 260, 210, 23);

        signup_name5.setBackground(new java.awt.Color(255, 255, 255));
        signup_name5.setFont(new java.awt.Font("Helvetica Neue", 0, 17)); // NOI18N
        signup_name5.setForeground(new java.awt.Color(102, 102, 102));
        signup_name5.setText("이건일 - 파트");
        signup.add(signup_name5);
        signup_name5.setBounds(50, 300, 210, 23);

        signup_deuProjectDescription1.setBackground(new java.awt.Color(204, 204, 204));
        signup_deuProjectDescription1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        signup_deuProjectDescription1.setForeground(new java.awt.Color(102, 102, 102));
        signup_deuProjectDescription1.setText("소프트웨어 공학 시간에 진행하는 자바로 구현 한 ");
        signup.add(signup_deuProjectDescription1);
        signup_deuProjectDescription1.setBounds(20, 460, 230, 20);

        signup_deuProjectDescription2.setBackground(new java.awt.Color(204, 204, 204));
        signup_deuProjectDescription2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        signup_deuProjectDescription2.setForeground(new java.awt.Color(102, 102, 102));
        signup_deuProjectDescription2.setText("빈 강의실 예약 프로그램 만들기 프로젝트 입니다.");
        signup.add(signup_deuProjectDescription2);
        signup_deuProjectDescription2.setBounds(20, 480, 230, 20);

        signup_githubLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/github.png"))); // NOI18N
        signup.add(signup_githubLogo);
        signup_githubLogo.setBounds(23, 512, 48, 50);

        signup_githubLogoTitle.setBackground(new java.awt.Color(255, 255, 255));
        signup_githubLogoTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        signup_githubLogoTitle.setForeground(new java.awt.Color(0, 0, 0));
        signup_githubLogoTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        signup_githubLogoTitle.setText("LectureRoomReservationSystem");
        signup.add(signup_githubLogoTitle);
        signup_githubLogoTitle.setBounds(80, 520, 170, 14);

        signup_githubButton.setBackground(new java.awt.Color(204, 204, 204));
        signup_githubButton.setForeground(new java.awt.Color(104, 104, 104));
        signup_githubButton.setText("이동하기");
        signup_githubButton.setToolTipText("");
        signup_githubButton.setRoundBottomLeft(10);
        signup_githubButton.setRoundBottomRight(10);
        signup_githubButton.setRoundTopLeft(10);
        signup_githubButton.setRoundTopRight(10);
        signup.add(signup_githubButton);
        signup_githubButton.setBounds(80, 540, 170, 20);

        signup_signupSideBarLabel.setBackground(new java.awt.Color(249, 249, 251));
        signup_signupSideBarLabel.setForeground(new java.awt.Color(249, 249, 251));
        signup.add(signup_signupSideBarLabel);
        signup_signupSideBarLabel.setBounds(0, 0, 270, 600);

        getContentPane().add(signup, "signup");
        signup.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // 컨트롤러 이벤트 등록
    public void addLoginListener(ActionListener listener) {
        login_loginButton.addActionListener(listener);
    }
    public void addSignupListener(ActionListener listener) {
        signup_signupButton.addActionListener(listener);
    }
    public void addSwitchToSignupListener(ActionListener listener) {
        login_signupButton.addActionListener(listener);
    }
    public void addSwitchToLoginListener(ActionListener listener) {
        signup_undoButton.addActionListener(listener);
    }

    // 사용자 설정 메서드
    public void showPanel(String name) {
        CardLayout layout = (CardLayout) getContentPane().getLayout();
        layout.show(getContentPane(), name);
    }
    public void addPanel(Component comp, String name) {
        getContentPane().add(comp, name);
    }
    public void clearSignupFields() {
        signup_signupNumberField.setText("");
        signup_signupPasswordField.setText("");
        signup_signupNameField.setText("");
        signup_signupMajorField.setText("");
    }
    public void transitionToHome(String userId, String userPw) {
        Home homePanel = new Home(userId, userPw);

        new HomeSwingController(homePanel);

        homePanel.setName("home");

        addPanel(homePanel, "home");
        showPanel("home");
    }
    public void switchToLoginPanel() {
        clearSignupFields();
        showPanel("login");
    }
    public void switchToSignupPanel() {
        clearSignupFields();
        showPanel("signup");
    }

    // 필드 값 전달
    public String getSignupId() {
        return signup_signupNumberField.getText().trim();
    }
    public String getSignupPassword() {
        return new String(signup_signupPasswordField.getText()).trim();
    }
    public String getSignupName() {
        return signup_signupNameField.getText().trim();
    }
    public String getSignupMajor() {
        return signup_signupMajorField.getText().trim();
    }
    public String getLoginId() {
        return login_loginNumberField.getText().trim();
    }
    public String getLoginPassword() {
        return new String(login_loginPasswordField.getPassword()).trim();
    }

    // 메시지 출력
    public void showError(String message) {
        JOptionPane.showMessageDialog(
                this,
                message,
                "오류",
                JOptionPane.ERROR_MESSAGE
        );
    }
    public void showSuccess(String message) {
        JOptionPane.showMessageDialog(
                this,
                message,
                "성공",
                JOptionPane.INFORMATION_MESSAGE
        );
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Auth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Auth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Auth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Auth.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Auth().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel login;
    private deu.view.custom.LabelRound login_SideBarLabel;
    private javax.swing.JLabel login_deuProjectDescription1;
    private javax.swing.JLabel login_deuProjectDescription2;
    private javax.swing.JLabel login_deuProjectLogo;
    private javax.swing.JLabel login_deuProjectTitle;
    private javax.swing.JLabel login_forgotPassword;
    private deu.view.custom.ButtonRound login_githubButton;
    private javax.swing.JLabel login_githubLogo;
    private javax.swing.JLabel login_githubLogoTitle;
    private deu.view.custom.ButtonRound login_loginButton;
    private javax.swing.JLabel login_loginDescription;
    private javax.swing.JLabel login_loginLogo;
    private deu.view.custom.TextFieldRound login_loginNumberField;
    private javax.swing.JLabel login_loginNumberLabel;
    private deu.view.custom.PasswordFieldRound login_loginPasswordField;
    private javax.swing.JLabel login_loginPasswordLabel;
    private javax.swing.JLabel login_loginTitle;
    private javax.swing.JLabel login_name1;
    private javax.swing.JLabel login_name2;
    private javax.swing.JLabel login_name3;
    private javax.swing.JLabel login_name4;
    private javax.swing.JLabel login_name5;
    private deu.view.custom.ButtonRound login_signupButton;
    private javax.swing.JLabel login_team1;
    private javax.swing.JLabel login_team2;
    private javax.swing.JPanel signup;
    private javax.swing.JLabel signup_deuProjectDescription1;
    private javax.swing.JLabel signup_deuProjectDescription2;
    private javax.swing.JLabel signup_deuProjectLogo;
    private javax.swing.JLabel signup_deuProjectTitle;
    private deu.view.custom.ButtonRound signup_githubButton;
    private javax.swing.JLabel signup_githubLogo;
    private javax.swing.JLabel signup_githubLogoTitle;
    private javax.swing.JLabel signup_loginLogo;
    private javax.swing.JLabel signup_loginNumberLabel;
    private javax.swing.JLabel signup_name1;
    private javax.swing.JLabel signup_name2;
    private javax.swing.JLabel signup_name3;
    private javax.swing.JLabel signup_name4;
    private javax.swing.JLabel signup_name5;
    private deu.view.custom.ButtonRound signup_signupButton;
    private javax.swing.JLabel signup_signupDescription;
    private deu.view.custom.TextFieldRound signup_signupMajorField;
    private javax.swing.JLabel signup_signupMajorLabel;
    private deu.view.custom.TextFieldRound signup_signupNameField;
    private javax.swing.JLabel signup_signupNameLabel;
    private deu.view.custom.TextFieldRound signup_signupNumberField;
    private deu.view.custom.TextFieldRound signup_signupPasswordField;
    private javax.swing.JLabel signup_signupPasswordLabel;
    private deu.view.custom.LabelRound signup_signupSideBarLabel;
    private javax.swing.JLabel signup_signupTitle;
    private javax.swing.JLabel signup_team1;
    private javax.swing.JLabel signup_team2;
    private deu.view.custom.ButtonRound signup_undoButton;
    // End of variables declaration//GEN-END:variables
}
