/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package deu.view;

import deu.controller.UserClientController;
import deu.model.dto.response.BasicResponse;
import lombok.Getter;
import lombok.Setter;

import java.awt.BorderLayout;
import java.awt.event.ActionListener;
import javax.swing.*;

/**
 *
 * @author oxxultus
 */
@Getter
@Setter
public class Home extends javax.swing.JPanel {

    private String userNumber;
    private String userPassword;

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    public Home(String userNumber, String userPassword) {
        this.userNumber = userNumber;
        this.userPassword = userPassword;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        managerMenu = new javax.swing.JPanel();
        logoutButton1 = new deu.view.custom.ButtonRound();
        reservationManagementButton = new deu.view.custom.ButtonRound();
        userManagementButton = new deu.view.custom.ButtonRound();
        deuLogo1 = new javax.swing.JLabel();
        concurrentUsers1 = new deu.view.custom.PanelRound();
        managerMenuCurrentUser = new javax.swing.JLabel();
        commonMenu = new deu.view.custom.ButtonRound();
        menu = new javax.swing.JPanel();
        logoutButton = new deu.view.custom.ButtonRound();
        myReservationMenu = new deu.view.custom.ButtonRound();
        LectureRoomReservationMenu = new deu.view.custom.ButtonRound();
        manegementMenu = new deu.view.custom.ButtonRound();
        deuLogo = new javax.swing.JLabel();
        concurrentUsers = new deu.view.custom.PanelRound();
        commonMenuCurrentUser = new javax.swing.JLabel();
        main = new javax.swing.JPanel();
        profilePanel = new deu.view.custom.PanelRound();
        profileImageField = new deu.view.custom.LabelRound();
        profileNumberField = new deu.view.custom.TextFieldRound();
        profileNameField = new deu.view.custom.TextFieldRound();
        reservationCountPanel = new deu.view.custom.PanelRound();
        reservationCountTitle = new javax.swing.JLabel();
        reservationCount = new javax.swing.JLabel();
        reservationTotalCountPanel = new deu.view.custom.PanelRound();
        reservationTotalCountTitle = new javax.swing.JLabel();
        reservationTotalCount = new javax.swing.JLabel();
        myReservationListPanel = new deu.view.custom.PanelRound();
        myReservationList = new javax.swing.JPanel();
        myReservationCalendar = new deu.view.custom.PanelRound();
        reservationInformationPanel = new deu.view.custom.PanelRound();
        buildingLabel = new javax.swing.JLabel();
        buildingField = new deu.view.custom.TextFieldRound();
        floorLabel = new javax.swing.JLabel();
        floorField = new deu.view.custom.TextFieldRound();
        lectureRoomLabel = new javax.swing.JLabel();
        lectureRoomField = new deu.view.custom.TextFieldRound();
        titleLabel = new javax.swing.JLabel();
        titleField = new deu.view.custom.TextFieldRound();
        descriptionLabel = new javax.swing.JLabel();
        descriptionField = new deu.view.custom.TextFieldRound();
        reservationUserNumberLabel = new javax.swing.JLabel();
        reservationUserNumberField = new deu.view.custom.TextFieldRound();
        updateButton = new deu.view.custom.ButtonRound();
        cancelButton = new deu.view.custom.ButtonRound();
        calendar = new javax.swing.JPanel();
        day0_0 = new deu.view.custom.ButtonRound();
        day1_0 = new deu.view.custom.ButtonRound();
        day2_0 = new deu.view.custom.ButtonRound();
        day3_0 = new deu.view.custom.ButtonRound();
        day4_0 = new deu.view.custom.ButtonRound();
        day5_0 = new deu.view.custom.ButtonRound();
        day6_0 = new deu.view.custom.ButtonRound();
        day0_1 = new deu.view.custom.ButtonRound();
        day1_1 = new deu.view.custom.ButtonRound();
        day2_1 = new deu.view.custom.ButtonRound();
        day3_1 = new deu.view.custom.ButtonRound();
        day4_1 = new deu.view.custom.ButtonRound();
        day5_1 = new deu.view.custom.ButtonRound();
        day6_1 = new deu.view.custom.ButtonRound();
        day0_2 = new deu.view.custom.ButtonRound();
        day1_2 = new deu.view.custom.ButtonRound();
        day2_2 = new deu.view.custom.ButtonRound();
        day3_2 = new deu.view.custom.ButtonRound();
        day4_2 = new deu.view.custom.ButtonRound();
        day5_2 = new deu.view.custom.ButtonRound();
        day6_2 = new deu.view.custom.ButtonRound();
        day0_3 = new deu.view.custom.ButtonRound();
        day1_3 = new deu.view.custom.ButtonRound();
        day2_3 = new deu.view.custom.ButtonRound();
        day3_3 = new deu.view.custom.ButtonRound();
        day4_3 = new deu.view.custom.ButtonRound();
        day5_3 = new deu.view.custom.ButtonRound();
        day6_3 = new deu.view.custom.ButtonRound();
        day0_4 = new deu.view.custom.ButtonRound();
        day1_4 = new deu.view.custom.ButtonRound();
        day2_4 = new deu.view.custom.ButtonRound();
        day3_4 = new deu.view.custom.ButtonRound();
        day4_4 = new deu.view.custom.ButtonRound();
        day5_4 = new deu.view.custom.ButtonRound();
        day6_4 = new deu.view.custom.ButtonRound();
        day0_5 = new deu.view.custom.ButtonRound();
        day1_5 = new deu.view.custom.ButtonRound();
        day2_5 = new deu.view.custom.ButtonRound();
        day3_5 = new deu.view.custom.ButtonRound();
        day4_5 = new deu.view.custom.ButtonRound();
        day5_5 = new deu.view.custom.ButtonRound();
        day6_5 = new deu.view.custom.ButtonRound();
        day0_6 = new deu.view.custom.ButtonRound();
        day1_6 = new deu.view.custom.ButtonRound();
        day2_6 = new deu.view.custom.ButtonRound();
        day3_6 = new deu.view.custom.ButtonRound();
        day4_6 = new deu.view.custom.ButtonRound();
        day5_6 = new deu.view.custom.ButtonRound();
        day6_6 = new deu.view.custom.ButtonRound();
        day0_7 = new deu.view.custom.ButtonRound();
        day1_7 = new deu.view.custom.ButtonRound();
        day2_7 = new deu.view.custom.ButtonRound();
        day3_7 = new deu.view.custom.ButtonRound();
        day4_7 = new deu.view.custom.ButtonRound();
        day5_7 = new deu.view.custom.ButtonRound();
        day6_7 = new deu.view.custom.ButtonRound();
        day0_8 = new deu.view.custom.ButtonRound();
        day1_8 = new deu.view.custom.ButtonRound();
        day2_8 = new deu.view.custom.ButtonRound();
        day3_8 = new deu.view.custom.ButtonRound();
        day4_8 = new deu.view.custom.ButtonRound();
        day5_8 = new deu.view.custom.ButtonRound();
        day6_8 = new deu.view.custom.ButtonRound();
        day0_9 = new deu.view.custom.ButtonRound();
        day1_9 = new deu.view.custom.ButtonRound();
        day2_9 = new deu.view.custom.ButtonRound();
        day3_9 = new deu.view.custom.ButtonRound();
        day4_9 = new deu.view.custom.ButtonRound();
        day5_9 = new deu.view.custom.ButtonRound();
        day6_9 = new deu.view.custom.ButtonRound();
        day0_10 = new deu.view.custom.ButtonRound();
        day1_10 = new deu.view.custom.ButtonRound();
        day2_10 = new deu.view.custom.ButtonRound();
        day3_10 = new deu.view.custom.ButtonRound();
        day4_10 = new deu.view.custom.ButtonRound();
        day5_10 = new deu.view.custom.ButtonRound();
        day6_10 = new deu.view.custom.ButtonRound();
        day0_11 = new deu.view.custom.ButtonRound();
        day1_11 = new deu.view.custom.ButtonRound();
        day2_11 = new deu.view.custom.ButtonRound();
        day3_11 = new deu.view.custom.ButtonRound();
        day4_11 = new deu.view.custom.ButtonRound();
        day5_11 = new deu.view.custom.ButtonRound();
        day6_11 = new deu.view.custom.ButtonRound();
        day0_12 = new deu.view.custom.ButtonRound();
        day1_12 = new deu.view.custom.ButtonRound();
        day2_12 = new deu.view.custom.ButtonRound();
        day3_12 = new deu.view.custom.ButtonRound();
        day4_12 = new deu.view.custom.ButtonRound();
        day5_12 = new deu.view.custom.ButtonRound();
        day6_12 = new deu.view.custom.ButtonRound();
        calendarDate = new javax.swing.JPanel();
        date0 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        calendarTime = new javax.swing.JPanel();
        time0 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        time6 = new javax.swing.JLabel();
        time7 = new javax.swing.JLabel();
        time8 = new javax.swing.JLabel();
        time9 = new javax.swing.JLabel();
        time10 = new javax.swing.JLabel();
        time11 = new javax.swing.JLabel();
        time12 = new javax.swing.JLabel();

        managerMenu.setBackground(new java.awt.Color(245, 245, 246));
        managerMenu.setPreferredSize(new java.awt.Dimension(1100, 50));
        managerMenu.setLayout(null);

        logoutButton1.setBackground(new java.awt.Color(221, 51, 65));
        logoutButton1.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton1.setText("로그아웃");
        logoutButton1.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        logoutButton1.setRoundBottomLeft(10);
        logoutButton1.setRoundBottomRight(10);
        logoutButton1.setRoundTopLeft(10);
        logoutButton1.setRoundTopRight(10);
        managerMenu.add(logoutButton1);
        logoutButton1.setBounds(1020, 10, 70, 30);

        reservationManagementButton.setBackground(new java.awt.Color(20, 90, 170));
        reservationManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        reservationManagementButton.setText("강의실 예약 관리");
        reservationManagementButton.setRoundBottomLeft(10);
        reservationManagementButton.setRoundBottomRight(0);
        reservationManagementButton.setRoundTopLeft(10);
        reservationManagementButton.setRoundTopRight(0);
        managerMenu.add(reservationManagementButton);
        reservationManagementButton.setBounds(160, 10, 180, 30);

        userManagementButton.setBackground(new java.awt.Color(20, 90, 170));
        userManagementButton.setForeground(new java.awt.Color(255, 255, 255));
        userManagementButton.setText("사용자 관리");
        userManagementButton.setRoundBottomLeft(0);
        userManagementButton.setRoundBottomRight(10);
        userManagementButton.setRoundTopLeft(0);
        userManagementButton.setRoundTopRight(10);
        managerMenu.add(userManagementButton);
        userManagementButton.setBounds(339, 10, 180, 30);

        deuLogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/deu-logo.png"))); // NOI18N
        managerMenu.add(deuLogo1);
        deuLogo1.setBounds(15, 5, 140, 40);

        concurrentUsers1.setBackground(new java.awt.Color(51, 51, 51));
        concurrentUsers1.setRoundBottomLeft(10);
        concurrentUsers1.setRoundBottomRight(10);
        concurrentUsers1.setRoundTopLeft(10);
        concurrentUsers1.setRoundTopRight(10);

        managerMenuCurrentUser.setBackground(new java.awt.Color(204, 204, 204));
        managerMenuCurrentUser.setForeground(new java.awt.Color(255, 255, 255));
        managerMenuCurrentUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        managerMenuCurrentUser.setText("1 명 접속중");
        managerMenuCurrentUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                managerMenuCurrentUserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout concurrentUsers1Layout = new javax.swing.GroupLayout(concurrentUsers1);
        concurrentUsers1.setLayout(concurrentUsers1Layout);
        concurrentUsers1Layout.setHorizontalGroup(
            concurrentUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concurrentUsers1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(managerMenuCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        concurrentUsers1Layout.setVerticalGroup(
            concurrentUsers1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concurrentUsers1Layout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(managerMenuCurrentUser)
                .addContainerGap())
        );

        managerMenu.add(concurrentUsers1);
        concurrentUsers1.setBounds(902, 10, 110, 30);

        commonMenu.setBackground(new java.awt.Color(221, 51, 65));
        commonMenu.setForeground(new java.awt.Color(255, 255, 255));
        commonMenu.setText("일반 메뉴");
        commonMenu.setRoundBottomLeft(10);
        commonMenu.setRoundBottomRight(10);
        commonMenu.setRoundTopLeft(10);
        commonMenu.setRoundTopRight(10);
        managerMenu.add(commonMenu);
        commonMenu.setBounds(580, 10, 112, 30);

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 600));
        setMinimumSize(new java.awt.Dimension(1100, 600));
        setLayout(new java.awt.BorderLayout());

        menu.setBackground(new java.awt.Color(245, 245, 246));
        menu.setPreferredSize(new java.awt.Dimension(1100, 50));
        menu.setLayout(null);

        logoutButton.setBackground(new java.awt.Color(221, 51, 65));
        logoutButton.setForeground(new java.awt.Color(255, 255, 255));
        logoutButton.setText("로그아웃");
        logoutButton.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        logoutButton.setRoundBottomLeft(10);
        logoutButton.setRoundBottomRight(10);
        logoutButton.setRoundTopLeft(10);
        logoutButton.setRoundTopRight(10);
        menu.add(logoutButton);
        logoutButton.setBounds(1020, 10, 70, 30);

        myReservationMenu.setBackground(new java.awt.Color(20, 90, 170));
        myReservationMenu.setForeground(new java.awt.Color(255, 255, 255));
        myReservationMenu.setText("내 예약 정보");
        myReservationMenu.setRoundBottomLeft(10);
        myReservationMenu.setRoundBottomRight(0);
        myReservationMenu.setRoundTopLeft(10);
        myReservationMenu.setRoundTopRight(0);
        menu.add(myReservationMenu);
        myReservationMenu.setBounds(160, 10, 180, 30);

        LectureRoomReservationMenu.setBackground(new java.awt.Color(20, 90, 170));
        LectureRoomReservationMenu.setForeground(new java.awt.Color(255, 255, 255));
        LectureRoomReservationMenu.setText("강의실 예약");
        LectureRoomReservationMenu.setRoundBottomLeft(0);
        LectureRoomReservationMenu.setRoundBottomRight(10);
        LectureRoomReservationMenu.setRoundTopLeft(0);
        LectureRoomReservationMenu.setRoundTopRight(10);
        menu.add(LectureRoomReservationMenu);
        LectureRoomReservationMenu.setBounds(339, 10, 180, 30);

        manegementMenu.setBackground(new java.awt.Color(20, 90, 170));
        manegementMenu.setForeground(new java.awt.Color(255, 255, 255));
        manegementMenu.setText("관리자 메뉴");
        manegementMenu.setRoundBottomLeft(10);
        manegementMenu.setRoundBottomRight(10);
        manegementMenu.setRoundTopLeft(10);
        manegementMenu.setRoundTopRight(10);
        menu.add(manegementMenu);
        manegementMenu.setBounds(580, 10, 112, 30);

        deuLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images-new/logo/deu-logo.png"))); // NOI18N
        menu.add(deuLogo);
        deuLogo.setBounds(15, 5, 140, 40);

        concurrentUsers.setBackground(new java.awt.Color(51, 51, 51));
        concurrentUsers.setRoundBottomLeft(10);
        concurrentUsers.setRoundBottomRight(10);
        concurrentUsers.setRoundTopLeft(10);
        concurrentUsers.setRoundTopRight(10);

        commonMenuCurrentUser.setBackground(new java.awt.Color(204, 204, 204));
        commonMenuCurrentUser.setForeground(new java.awt.Color(255, 255, 255));
        commonMenuCurrentUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        commonMenuCurrentUser.setText("0 명 접속중");
        commonMenuCurrentUser.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                commonMenuCurrentUserAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout concurrentUsersLayout = new javax.swing.GroupLayout(concurrentUsers);
        concurrentUsers.setLayout(concurrentUsersLayout);
        concurrentUsersLayout.setHorizontalGroup(
            concurrentUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concurrentUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(commonMenuCurrentUser, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        concurrentUsersLayout.setVerticalGroup(
            concurrentUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, concurrentUsersLayout.createSequentialGroup()
                .addContainerGap(7, Short.MAX_VALUE)
                .addComponent(commonMenuCurrentUser)
                .addContainerGap())
        );

        menu.add(concurrentUsers);
        concurrentUsers.setBounds(902, 10, 110, 30);

        add(menu, java.awt.BorderLayout.PAGE_START);

        main.setBackground(new java.awt.Color(255, 255, 255));
        main.setForeground(new java.awt.Color(255, 255, 255));
        main.setLayout(null);

        profilePanel.setBackground(new java.awt.Color(20, 90, 170));
        profilePanel.setRoundBottomLeft(15);
        profilePanel.setRoundBottomRight(15);
        profilePanel.setRoundTopLeft(15);
        profilePanel.setRoundTopRight(15);
        profilePanel.setLayout(null);

        profileImageField.setBackground(new java.awt.Color(51, 51, 51));
        profileImageField.setForeground(new java.awt.Color(60, 63, 65));
        profileImageField.setRoundBottomLeft(30);
        profileImageField.setRoundBottomRight(30);
        profileImageField.setRoundTopLeft(30);
        profileImageField.setRoundTopRight(30);
        profilePanel.add(profileImageField);
        profileImageField.setBounds(10, 10, 115, 95);

        profileNumberField.setEditable(false);
        profileNumberField.setBackground(new java.awt.Color(255, 255, 255));
        profileNumberField.setForeground(new java.awt.Color(0, 0, 0));
        profileNumberField.setRound(10);
        profilePanel.add(profileNumberField);
        profileNumberField.setBounds(140, 30, 110, 27);

        profileNameField.setEditable(false);
        profileNameField.setBackground(new java.awt.Color(255, 255, 255));
        profileNameField.setForeground(new java.awt.Color(0, 0, 0));
        profileNameField.setRound(10);
        profilePanel.add(profileNameField);
        profileNameField.setBounds(140, 70, 110, 27);

        reservationCountPanel.setBackground(new java.awt.Color(51, 51, 51));
        reservationCountPanel.setForeground(new java.awt.Color(60, 63, 65));
        reservationCountPanel.setRoundBottomLeft(10);
        reservationCountPanel.setRoundBottomRight(10);
        reservationCountPanel.setRoundTopLeft(10);
        reservationCountPanel.setRoundTopRight(10);
        reservationCountPanel.setLayout(null);

        reservationCountTitle.setBackground(new java.awt.Color(204, 204, 204));
        reservationCountTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        reservationCountTitle.setForeground(new java.awt.Color(255, 255, 255));
        reservationCountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationCountTitle.setText("예약");
        reservationCountPanel.add(reservationCountTitle);
        reservationCountTitle.setBounds(0, 44, 115, 10);

        reservationCount.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        reservationCount.setForeground(new java.awt.Color(255, 255, 255));
        reservationCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationCount.setText("1");
        reservationCountPanel.add(reservationCount);
        reservationCount.setBounds(2, 10, 113, 30);

        profilePanel.add(reservationCountPanel);
        reservationCountPanel.setBounds(10, 120, 115, 60);

        reservationTotalCountPanel.setBackground(new java.awt.Color(51, 51, 51));
        reservationTotalCountPanel.setForeground(new java.awt.Color(60, 63, 65));
        reservationTotalCountPanel.setRoundBottomLeft(10);
        reservationTotalCountPanel.setRoundBottomRight(10);
        reservationTotalCountPanel.setRoundTopLeft(10);
        reservationTotalCountPanel.setRoundTopRight(10);
        reservationTotalCountPanel.setLayout(null);

        reservationTotalCountTitle.setBackground(new java.awt.Color(204, 204, 204));
        reservationTotalCountTitle.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        reservationTotalCountTitle.setForeground(new java.awt.Color(255, 255, 255));
        reservationTotalCountTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationTotalCountTitle.setText("잔여 예약");
        reservationTotalCountPanel.add(reservationTotalCountTitle);
        reservationTotalCountTitle.setBounds(0, 44, 115, 10);

        reservationTotalCount.setFont(new java.awt.Font("Helvetica Neue", 0, 20)); // NOI18N
        reservationTotalCount.setForeground(new java.awt.Color(255, 255, 255));
        reservationTotalCount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationTotalCount.setText("4");
        reservationTotalCount.setToolTipText("");
        reservationTotalCountPanel.add(reservationTotalCount);
        reservationTotalCount.setBounds(2, 10, 113, 30);

        profilePanel.add(reservationTotalCountPanel);
        reservationTotalCountPanel.setBounds(135, 120, 115, 60);

        main.add(profilePanel);
        profilePanel.setBounds(6, 6, 260, 190);

        myReservationListPanel.setBackground(new java.awt.Color(255, 255, 255));
        myReservationListPanel.setForeground(new java.awt.Color(255, 255, 255));
        myReservationListPanel.setBorderColor(java.awt.Color.black);
        myReservationListPanel.setRoundBottomLeft(15);
        myReservationListPanel.setRoundBottomRight(15);
        myReservationListPanel.setRoundTopLeft(15);
        myReservationListPanel.setRoundTopRight(15);
        myReservationListPanel.setLayout(null);

        myReservationList.setBackground(new java.awt.Color(255, 255, 255));
        myReservationList.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                myReservationListAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        myReservationList.setLayout(new java.awt.GridLayout(5, 1, 0, 10));
        myReservationListPanel.add(myReservationList);
        myReservationList.setBounds(10, 10, 240, 320);

        main.add(myReservationListPanel);
        myReservationListPanel.setBounds(6, 200, 260, 340);

        myReservationCalendar.setBackground(new java.awt.Color(255, 255, 255));
        myReservationCalendar.setBorderColor(java.awt.Color.black);
        myReservationCalendar.setRoundBottomLeft(15);
        myReservationCalendar.setRoundBottomRight(15);
        myReservationCalendar.setRoundTopLeft(15);
        myReservationCalendar.setRoundTopRight(15);
        myReservationCalendar.setLayout(null);

        reservationInformationPanel.setBackground(new java.awt.Color(20, 90, 170));
        reservationInformationPanel.setRoundBottomLeft(10);
        reservationInformationPanel.setRoundBottomRight(10);
        reservationInformationPanel.setRoundTopLeft(10);
        reservationInformationPanel.setRoundTopRight(10);
        reservationInformationPanel.setLayout(null);

        buildingLabel.setForeground(new java.awt.Color(255, 255, 255));
        buildingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingLabel.setText("건물");
        reservationInformationPanel.add(buildingLabel);
        buildingLabel.setBounds(10, 10, 40, 20);

        buildingField.setEditable(false);
        buildingField.setBackground(new java.awt.Color(255, 255, 255));
        buildingField.setForeground(new java.awt.Color(0, 0, 0));
        buildingField.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        buildingField.setRound(10);
        reservationInformationPanel.add(buildingField);
        buildingField.setBounds(50, 10, 120, 20);

        floorLabel.setForeground(new java.awt.Color(255, 255, 255));
        floorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorLabel.setText("층");
        reservationInformationPanel.add(floorLabel);
        floorLabel.setBounds(10, 40, 40, 20);

        floorField.setEditable(false);
        floorField.setBackground(new java.awt.Color(255, 255, 255));
        floorField.setForeground(new java.awt.Color(0, 0, 0));
        floorField.setRound(10);
        reservationInformationPanel.add(floorField);
        floorField.setBounds(50, 40, 120, 20);

        lectureRoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        lectureRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lectureRoomLabel.setText("강의실");
        reservationInformationPanel.add(lectureRoomLabel);
        lectureRoomLabel.setBounds(180, 10, 40, 20);

        lectureRoomField.setEditable(false);
        lectureRoomField.setBackground(new java.awt.Color(255, 255, 255));
        lectureRoomField.setForeground(new java.awt.Color(0, 0, 0));
        lectureRoomField.setRound(10);
        reservationInformationPanel.add(lectureRoomField);
        lectureRoomField.setBounds(220, 10, 120, 20);

        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("제목");
        reservationInformationPanel.add(titleLabel);
        titleLabel.setBounds(350, 10, 40, 20);

        titleField.setEditable(false);
        titleField.setBackground(new java.awt.Color(255, 255, 255));
        titleField.setForeground(new java.awt.Color(0, 0, 0));
        titleField.setRound(10);
        reservationInformationPanel.add(titleField);
        titleField.setBounds(390, 10, 300, 20);

        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("설명");
        reservationInformationPanel.add(descriptionLabel);
        descriptionLabel.setBounds(350, 40, 40, 20);

        descriptionField.setEditable(false);
        descriptionField.setBackground(new java.awt.Color(255, 255, 255));
        descriptionField.setForeground(new java.awt.Color(0, 0, 0));
        descriptionField.setRound(10);
        reservationInformationPanel.add(descriptionField);
        descriptionField.setBounds(390, 40, 300, 20);

        reservationUserNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationUserNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationUserNumberLabel.setText("예약자");
        reservationInformationPanel.add(reservationUserNumberLabel);
        reservationUserNumberLabel.setBounds(180, 40, 40, 20);

        reservationUserNumberField.setEditable(false);
        reservationUserNumberField.setBackground(new java.awt.Color(255, 255, 255));
        reservationUserNumberField.setForeground(new java.awt.Color(0, 0, 0));
        reservationUserNumberField.setFont(new java.awt.Font("Helvetica Neue", 0, 10)); // NOI18N
        reservationUserNumberField.setRound(10);
        reservationInformationPanel.add(reservationUserNumberField);
        reservationUserNumberField.setBounds(220, 40, 120, 20);

        updateButton.setBackground(new java.awt.Color(0, 102, 255));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("저장하기");
        updateButton.setBorderColor(null);
        updateButton.setRoundBottomLeft(10);
        updateButton.setRoundBottomRight(10);
        updateButton.setRoundTopLeft(10);
        updateButton.setRoundTopRight(10);
        reservationInformationPanel.add(updateButton);
        updateButton.setBounds(700, 10, 90, 20);

        cancelButton.setBackground(new java.awt.Color(102, 102, 102));
        cancelButton.setForeground(new java.awt.Color(255, 255, 255));
        cancelButton.setText(" 취소하기");
        cancelButton.setBorderColor(null);
        cancelButton.setRoundBottomLeft(10);
        cancelButton.setRoundBottomRight(10);
        cancelButton.setRoundTopLeft(10);
        cancelButton.setRoundTopRight(10);
        reservationInformationPanel.add(cancelButton);
        cancelButton.setBounds(700, 40, 90, 20);

        myReservationCalendar.add(reservationInformationPanel);
        reservationInformationPanel.setBounds(10, 10, 800, 70);

        calendar.setBackground(new java.awt.Color(255, 255, 255));
        calendar.setLayout(new java.awt.GridLayout(13, 7, 3, 3));

        day0_0.setBackground(new java.awt.Color(245, 245, 246));
        day0_0.setForeground(new java.awt.Color(0, 0, 0));
        day0_0.setBorderColor(java.awt.Color.darkGray);
        day0_0.setBorderPainted(true);
        day0_0.setName("day0_0"); // NOI18N
        day0_0.setRoundBottomLeft(13);
        day0_0.setRoundBottomRight(13);
        day0_0.setRoundTopLeft(13);
        day0_0.setRoundTopRight(13);
        calendar.add(day0_0);

        day1_0.setBackground(new java.awt.Color(245, 245, 246));
        day1_0.setForeground(new java.awt.Color(0, 0, 0));
        day1_0.setBorderColor(java.awt.Color.darkGray);
        day1_0.setBorderPainted(true);
        day1_0.setName("day1_0"); // NOI18N
        day1_0.setRoundBottomLeft(13);
        day1_0.setRoundBottomRight(13);
        day1_0.setRoundTopLeft(13);
        day1_0.setRoundTopRight(13);
        calendar.add(day1_0);

        day2_0.setBackground(new java.awt.Color(245, 245, 246));
        day2_0.setForeground(new java.awt.Color(0, 0, 0));
        day2_0.setBorderColor(java.awt.Color.darkGray);
        day2_0.setBorderPainted(true);
        day2_0.setName("day2_0"); // NOI18N
        day2_0.setRoundBottomLeft(13);
        day2_0.setRoundBottomRight(13);
        day2_0.setRoundTopLeft(13);
        day2_0.setRoundTopRight(13);
        calendar.add(day2_0);

        day3_0.setBackground(new java.awt.Color(245, 245, 246));
        day3_0.setForeground(new java.awt.Color(0, 0, 0));
        day3_0.setBorderColor(java.awt.Color.darkGray);
        day3_0.setBorderPainted(true);
        day3_0.setName("day3_0"); // NOI18N
        day3_0.setRoundBottomLeft(13);
        day3_0.setRoundBottomRight(13);
        day3_0.setRoundTopLeft(13);
        day3_0.setRoundTopRight(13);
        calendar.add(day3_0);

        day4_0.setBackground(new java.awt.Color(245, 245, 246));
        day4_0.setForeground(new java.awt.Color(0, 0, 0));
        day4_0.setBorderColor(java.awt.Color.darkGray);
        day4_0.setBorderPainted(true);
        day4_0.setName("day4_0"); // NOI18N
        day4_0.setRoundBottomLeft(13);
        day4_0.setRoundBottomRight(13);
        day4_0.setRoundTopLeft(13);
        day4_0.setRoundTopRight(13);
        calendar.add(day4_0);

        day5_0.setBackground(new java.awt.Color(245, 245, 246));
        day5_0.setForeground(new java.awt.Color(0, 0, 0));
        day5_0.setBorderColor(java.awt.Color.darkGray);
        day5_0.setBorderPainted(true);
        day5_0.setName("day4_0"); // NOI18N
        day5_0.setRoundBottomLeft(13);
        day5_0.setRoundBottomRight(13);
        day5_0.setRoundTopLeft(13);
        day5_0.setRoundTopRight(13);
        calendar.add(day5_0);

        day6_0.setBackground(new java.awt.Color(245, 245, 246));
        day6_0.setForeground(new java.awt.Color(0, 0, 0));
        day6_0.setBorderColor(java.awt.Color.darkGray);
        day6_0.setBorderPainted(true);
        day6_0.setName("day6_0"); // NOI18N
        day6_0.setRoundBottomLeft(13);
        day6_0.setRoundBottomRight(13);
        day6_0.setRoundTopLeft(13);
        day6_0.setRoundTopRight(13);
        calendar.add(day6_0);

        day0_1.setBackground(new java.awt.Color(245, 245, 246));
        day0_1.setForeground(new java.awt.Color(0, 0, 0));
        day0_1.setBorderColor(java.awt.Color.darkGray);
        day0_1.setBorderPainted(true);
        day0_1.setName("day0_1"); // NOI18N
        day0_1.setRoundBottomLeft(13);
        day0_1.setRoundBottomRight(13);
        day0_1.setRoundTopLeft(13);
        day0_1.setRoundTopRight(13);
        calendar.add(day0_1);

        day1_1.setBackground(new java.awt.Color(245, 245, 246));
        day1_1.setForeground(new java.awt.Color(0, 0, 0));
        day1_1.setBorderColor(java.awt.Color.darkGray);
        day1_1.setBorderPainted(true);
        day1_1.setName("day1_1"); // NOI18N
        day1_1.setRoundBottomLeft(13);
        day1_1.setRoundBottomRight(13);
        day1_1.setRoundTopLeft(13);
        day1_1.setRoundTopRight(13);
        calendar.add(day1_1);

        day2_1.setBackground(new java.awt.Color(245, 245, 246));
        day2_1.setForeground(new java.awt.Color(0, 0, 0));
        day2_1.setBorderColor(java.awt.Color.darkGray);
        day2_1.setBorderPainted(true);
        day2_1.setName("day2_1"); // NOI18N
        day2_1.setRoundBottomLeft(13);
        day2_1.setRoundBottomRight(13);
        day2_1.setRoundTopLeft(13);
        day2_1.setRoundTopRight(13);
        calendar.add(day2_1);

        day3_1.setBackground(new java.awt.Color(245, 245, 246));
        day3_1.setForeground(new java.awt.Color(0, 0, 0));
        day3_1.setBorderColor(java.awt.Color.darkGray);
        day3_1.setBorderPainted(true);
        day3_1.setName("day3_1"); // NOI18N
        day3_1.setRoundBottomLeft(13);
        day3_1.setRoundBottomRight(13);
        day3_1.setRoundTopLeft(13);
        day3_1.setRoundTopRight(13);
        calendar.add(day3_1);

        day4_1.setBackground(new java.awt.Color(245, 245, 246));
        day4_1.setForeground(new java.awt.Color(0, 0, 0));
        day4_1.setBorderColor(java.awt.Color.darkGray);
        day4_1.setBorderPainted(true);
        day4_1.setName("day4_1"); // NOI18N
        day4_1.setRoundBottomLeft(13);
        day4_1.setRoundBottomRight(13);
        day4_1.setRoundTopLeft(13);
        day4_1.setRoundTopRight(13);
        calendar.add(day4_1);

        day5_1.setBackground(new java.awt.Color(245, 245, 246));
        day5_1.setForeground(new java.awt.Color(0, 0, 0));
        day5_1.setBorderColor(java.awt.Color.darkGray);
        day5_1.setBorderPainted(true);
        day5_1.setName("day5_1"); // NOI18N
        day5_1.setRoundBottomLeft(13);
        day5_1.setRoundBottomRight(13);
        day5_1.setRoundTopLeft(13);
        day5_1.setRoundTopRight(13);
        calendar.add(day5_1);

        day6_1.setBackground(new java.awt.Color(245, 245, 246));
        day6_1.setForeground(new java.awt.Color(0, 0, 0));
        day6_1.setBorderColor(java.awt.Color.darkGray);
        day6_1.setBorderPainted(true);
        day6_1.setName("day6_1"); // NOI18N
        day6_1.setRoundBottomLeft(13);
        day6_1.setRoundBottomRight(13);
        day6_1.setRoundTopLeft(13);
        day6_1.setRoundTopRight(13);
        calendar.add(day6_1);

        day0_2.setBackground(new java.awt.Color(245, 245, 246));
        day0_2.setForeground(new java.awt.Color(0, 0, 0));
        day0_2.setBorderColor(java.awt.Color.darkGray);
        day0_2.setBorderPainted(true);
        day0_2.setName("day0_2"); // NOI18N
        day0_2.setRoundBottomLeft(13);
        day0_2.setRoundBottomRight(13);
        day0_2.setRoundTopLeft(13);
        day0_2.setRoundTopRight(13);
        calendar.add(day0_2);

        day1_2.setBackground(new java.awt.Color(245, 245, 246));
        day1_2.setForeground(new java.awt.Color(0, 0, 0));
        day1_2.setBorderColor(java.awt.Color.darkGray);
        day1_2.setBorderPainted(true);
        day1_2.setName("day1_2"); // NOI18N
        day1_2.setRoundBottomLeft(13);
        day1_2.setRoundBottomRight(13);
        day1_2.setRoundTopLeft(13);
        day1_2.setRoundTopRight(13);
        calendar.add(day1_2);

        day2_2.setBackground(new java.awt.Color(245, 245, 246));
        day2_2.setForeground(new java.awt.Color(0, 0, 0));
        day2_2.setBorderColor(java.awt.Color.darkGray);
        day2_2.setBorderPainted(true);
        day2_2.setName("day2_2"); // NOI18N
        day2_2.setRoundBottomLeft(13);
        day2_2.setRoundBottomRight(13);
        day2_2.setRoundTopLeft(13);
        day2_2.setRoundTopRight(13);
        calendar.add(day2_2);

        day3_2.setBackground(new java.awt.Color(245, 245, 246));
        day3_2.setForeground(new java.awt.Color(0, 0, 0));
        day3_2.setBorderColor(java.awt.Color.darkGray);
        day3_2.setBorderPainted(true);
        day3_2.setName("day3_2"); // NOI18N
        day3_2.setRoundBottomLeft(13);
        day3_2.setRoundBottomRight(13);
        day3_2.setRoundTopLeft(13);
        day3_2.setRoundTopRight(13);
        calendar.add(day3_2);

        day4_2.setBackground(new java.awt.Color(245, 245, 246));
        day4_2.setForeground(new java.awt.Color(0, 0, 0));
        day4_2.setBorderColor(java.awt.Color.darkGray);
        day4_2.setBorderPainted(true);
        day4_2.setName("day4_2"); // NOI18N
        day4_2.setRoundBottomLeft(13);
        day4_2.setRoundBottomRight(13);
        day4_2.setRoundTopLeft(13);
        day4_2.setRoundTopRight(13);
        calendar.add(day4_2);

        day5_2.setBackground(new java.awt.Color(245, 245, 246));
        day5_2.setForeground(new java.awt.Color(0, 0, 0));
        day5_2.setBorderColor(java.awt.Color.darkGray);
        day5_2.setBorderPainted(true);
        day5_2.setName("day5_2"); // NOI18N
        day5_2.setRoundBottomLeft(13);
        day5_2.setRoundBottomRight(13);
        day5_2.setRoundTopLeft(13);
        day5_2.setRoundTopRight(13);
        calendar.add(day5_2);

        day6_2.setBackground(new java.awt.Color(245, 245, 246));
        day6_2.setForeground(new java.awt.Color(0, 0, 0));
        day6_2.setBorderColor(java.awt.Color.darkGray);
        day6_2.setBorderPainted(true);
        day6_2.setName("day6_2"); // NOI18N
        day6_2.setRoundBottomLeft(13);
        day6_2.setRoundBottomRight(13);
        day6_2.setRoundTopLeft(13);
        day6_2.setRoundTopRight(13);
        calendar.add(day6_2);

        day0_3.setBackground(new java.awt.Color(245, 245, 246));
        day0_3.setForeground(new java.awt.Color(0, 0, 0));
        day0_3.setBorderColor(java.awt.Color.darkGray);
        day0_3.setBorderPainted(true);
        day0_3.setName("day0_3"); // NOI18N
        day0_3.setRoundBottomLeft(13);
        day0_3.setRoundBottomRight(13);
        day0_3.setRoundTopLeft(13);
        day0_3.setRoundTopRight(13);
        calendar.add(day0_3);

        day1_3.setBackground(new java.awt.Color(245, 245, 246));
        day1_3.setForeground(new java.awt.Color(0, 0, 0));
        day1_3.setBorderColor(java.awt.Color.darkGray);
        day1_3.setBorderPainted(true);
        day1_3.setName("day1_3"); // NOI18N
        day1_3.setRoundBottomLeft(13);
        day1_3.setRoundBottomRight(13);
        day1_3.setRoundTopLeft(13);
        day1_3.setRoundTopRight(13);
        calendar.add(day1_3);

        day2_3.setBackground(new java.awt.Color(245, 245, 246));
        day2_3.setForeground(new java.awt.Color(0, 0, 0));
        day2_3.setBorderColor(java.awt.Color.darkGray);
        day2_3.setBorderPainted(true);
        day2_3.setName("day2_3"); // NOI18N
        day2_3.setRoundBottomLeft(13);
        day2_3.setRoundBottomRight(13);
        day2_3.setRoundTopLeft(13);
        day2_3.setRoundTopRight(13);
        calendar.add(day2_3);

        day3_3.setBackground(new java.awt.Color(245, 245, 246));
        day3_3.setForeground(new java.awt.Color(0, 0, 0));
        day3_3.setBorderColor(java.awt.Color.darkGray);
        day3_3.setBorderPainted(true);
        day3_3.setName("day3_3"); // NOI18N
        day3_3.setRoundBottomLeft(13);
        day3_3.setRoundBottomRight(13);
        day3_3.setRoundTopLeft(13);
        day3_3.setRoundTopRight(13);
        calendar.add(day3_3);

        day4_3.setBackground(new java.awt.Color(245, 245, 246));
        day4_3.setForeground(new java.awt.Color(0, 0, 0));
        day4_3.setBorderColor(java.awt.Color.darkGray);
        day4_3.setBorderPainted(true);
        day4_3.setName("day4_3"); // NOI18N
        day4_3.setRoundBottomLeft(13);
        day4_3.setRoundBottomRight(13);
        day4_3.setRoundTopLeft(13);
        day4_3.setRoundTopRight(13);
        calendar.add(day4_3);

        day5_3.setBackground(new java.awt.Color(245, 245, 246));
        day5_3.setForeground(new java.awt.Color(0, 0, 0));
        day5_3.setBorderColor(java.awt.Color.darkGray);
        day5_3.setBorderPainted(true);
        day5_3.setName("day5_3"); // NOI18N
        day5_3.setRoundBottomLeft(13);
        day5_3.setRoundBottomRight(13);
        day5_3.setRoundTopLeft(13);
        day5_3.setRoundTopRight(13);
        calendar.add(day5_3);

        day6_3.setBackground(new java.awt.Color(245, 245, 246));
        day6_3.setForeground(new java.awt.Color(0, 0, 0));
        day6_3.setBorderColor(java.awt.Color.darkGray);
        day6_3.setBorderPainted(true);
        day6_3.setName("day6_3"); // NOI18N
        day6_3.setRoundBottomLeft(13);
        day6_3.setRoundBottomRight(13);
        day6_3.setRoundTopLeft(13);
        day6_3.setRoundTopRight(13);
        calendar.add(day6_3);

        day0_4.setBackground(new java.awt.Color(245, 245, 246));
        day0_4.setForeground(new java.awt.Color(0, 0, 0));
        day0_4.setBorderColor(java.awt.Color.darkGray);
        day0_4.setBorderPainted(true);
        day0_4.setName("day0_4"); // NOI18N
        day0_4.setRoundBottomLeft(13);
        day0_4.setRoundBottomRight(13);
        day0_4.setRoundTopLeft(13);
        day0_4.setRoundTopRight(13);
        calendar.add(day0_4);

        day1_4.setBackground(new java.awt.Color(245, 245, 246));
        day1_4.setForeground(new java.awt.Color(0, 0, 0));
        day1_4.setBorderColor(java.awt.Color.darkGray);
        day1_4.setBorderPainted(true);
        day1_4.setName("day1_4"); // NOI18N
        day1_4.setRoundBottomLeft(13);
        day1_4.setRoundBottomRight(13);
        day1_4.setRoundTopLeft(13);
        day1_4.setRoundTopRight(13);
        calendar.add(day1_4);

        day2_4.setBackground(new java.awt.Color(245, 245, 246));
        day2_4.setForeground(new java.awt.Color(0, 0, 0));
        day2_4.setBorderColor(java.awt.Color.darkGray);
        day2_4.setBorderPainted(true);
        day2_4.setName("day2_4"); // NOI18N
        day2_4.setRoundBottomLeft(13);
        day2_4.setRoundBottomRight(13);
        day2_4.setRoundTopLeft(13);
        day2_4.setRoundTopRight(13);
        calendar.add(day2_4);

        day3_4.setBackground(new java.awt.Color(245, 245, 246));
        day3_4.setForeground(new java.awt.Color(0, 0, 0));
        day3_4.setBorderColor(java.awt.Color.darkGray);
        day3_4.setBorderPainted(true);
        day3_4.setName("day3_4"); // NOI18N
        day3_4.setRoundBottomLeft(13);
        day3_4.setRoundBottomRight(13);
        day3_4.setRoundTopLeft(13);
        day3_4.setRoundTopRight(13);
        calendar.add(day3_4);

        day4_4.setBackground(new java.awt.Color(245, 245, 246));
        day4_4.setForeground(new java.awt.Color(0, 0, 0));
        day4_4.setBorderColor(java.awt.Color.darkGray);
        day4_4.setBorderPainted(true);
        day4_4.setName("day4_4"); // NOI18N
        day4_4.setRoundBottomLeft(13);
        day4_4.setRoundBottomRight(13);
        day4_4.setRoundTopLeft(13);
        day4_4.setRoundTopRight(13);
        calendar.add(day4_4);

        day5_4.setBackground(new java.awt.Color(245, 245, 246));
        day5_4.setForeground(new java.awt.Color(0, 0, 0));
        day5_4.setBorderColor(java.awt.Color.darkGray);
        day5_4.setBorderPainted(true);
        day5_4.setName("day5_4"); // NOI18N
        day5_4.setRoundBottomLeft(13);
        day5_4.setRoundBottomRight(13);
        day5_4.setRoundTopLeft(13);
        day5_4.setRoundTopRight(13);
        calendar.add(day5_4);

        day6_4.setBackground(new java.awt.Color(245, 245, 246));
        day6_4.setForeground(new java.awt.Color(0, 0, 0));
        day6_4.setBorderColor(java.awt.Color.darkGray);
        day6_4.setBorderPainted(true);
        day6_4.setName("day6_4"); // NOI18N
        day6_4.setRoundBottomLeft(13);
        day6_4.setRoundBottomRight(13);
        day6_4.setRoundTopLeft(13);
        day6_4.setRoundTopRight(13);
        calendar.add(day6_4);

        day0_5.setBackground(new java.awt.Color(245, 245, 246));
        day0_5.setForeground(new java.awt.Color(0, 0, 0));
        day0_5.setBorderColor(java.awt.Color.darkGray);
        day0_5.setBorderPainted(true);
        day0_5.setName("day0_5"); // NOI18N
        day0_5.setRoundBottomLeft(13);
        day0_5.setRoundBottomRight(13);
        day0_5.setRoundTopLeft(13);
        day0_5.setRoundTopRight(13);
        calendar.add(day0_5);

        day1_5.setBackground(new java.awt.Color(245, 245, 246));
        day1_5.setForeground(new java.awt.Color(0, 0, 0));
        day1_5.setBorderColor(java.awt.Color.darkGray);
        day1_5.setBorderPainted(true);
        day1_5.setName("day1_5"); // NOI18N
        day1_5.setRoundBottomLeft(13);
        day1_5.setRoundBottomRight(13);
        day1_5.setRoundTopLeft(13);
        day1_5.setRoundTopRight(13);
        calendar.add(day1_5);

        day2_5.setBackground(new java.awt.Color(245, 245, 246));
        day2_5.setForeground(new java.awt.Color(0, 0, 0));
        day2_5.setBorderColor(java.awt.Color.darkGray);
        day2_5.setBorderPainted(true);
        day2_5.setName("day2_5"); // NOI18N
        day2_5.setRoundBottomLeft(13);
        day2_5.setRoundBottomRight(13);
        day2_5.setRoundTopLeft(13);
        day2_5.setRoundTopRight(13);
        calendar.add(day2_5);

        day3_5.setBackground(new java.awt.Color(245, 245, 246));
        day3_5.setForeground(new java.awt.Color(0, 0, 0));
        day3_5.setBorderColor(java.awt.Color.darkGray);
        day3_5.setBorderPainted(true);
        day3_5.setName("day3_5"); // NOI18N
        day3_5.setRoundBottomLeft(13);
        day3_5.setRoundBottomRight(13);
        day3_5.setRoundTopLeft(13);
        day3_5.setRoundTopRight(13);
        calendar.add(day3_5);

        day4_5.setBackground(new java.awt.Color(245, 245, 246));
        day4_5.setForeground(new java.awt.Color(0, 0, 0));
        day4_5.setBorderColor(java.awt.Color.darkGray);
        day4_5.setBorderPainted(true);
        day4_5.setName("day4_5"); // NOI18N
        day4_5.setRoundBottomLeft(13);
        day4_5.setRoundBottomRight(13);
        day4_5.setRoundTopLeft(13);
        day4_5.setRoundTopRight(13);
        calendar.add(day4_5);

        day5_5.setBackground(new java.awt.Color(245, 245, 246));
        day5_5.setForeground(new java.awt.Color(0, 0, 0));
        day5_5.setBorderColor(java.awt.Color.darkGray);
        day5_5.setBorderPainted(true);
        day5_5.setName("day5_5"); // NOI18N
        day5_5.setRoundBottomLeft(13);
        day5_5.setRoundBottomRight(13);
        day5_5.setRoundTopLeft(13);
        day5_5.setRoundTopRight(13);
        calendar.add(day5_5);

        day6_5.setBackground(new java.awt.Color(245, 245, 246));
        day6_5.setForeground(new java.awt.Color(0, 0, 0));
        day6_5.setBorderColor(java.awt.Color.darkGray);
        day6_5.setBorderPainted(true);
        day6_5.setName("day6_5"); // NOI18N
        day6_5.setRoundBottomLeft(13);
        day6_5.setRoundBottomRight(13);
        day6_5.setRoundTopLeft(13);
        day6_5.setRoundTopRight(13);
        calendar.add(day6_5);

        day0_6.setBackground(new java.awt.Color(245, 245, 246));
        day0_6.setForeground(new java.awt.Color(0, 0, 0));
        day0_6.setBorderColor(java.awt.Color.darkGray);
        day0_6.setBorderPainted(true);
        day0_6.setName("day0_6"); // NOI18N
        day0_6.setOpaque(true);
        day0_6.setRoundBottomLeft(13);
        day0_6.setRoundBottomRight(13);
        day0_6.setRoundTopLeft(13);
        day0_6.setRoundTopRight(13);
        calendar.add(day0_6);

        day1_6.setBackground(new java.awt.Color(245, 245, 246));
        day1_6.setForeground(new java.awt.Color(0, 0, 0));
        day1_6.setBorderColor(java.awt.Color.darkGray);
        day1_6.setBorderPainted(true);
        day1_6.setName("day1_6"); // NOI18N
        day1_6.setRoundBottomLeft(13);
        day1_6.setRoundBottomRight(13);
        day1_6.setRoundTopLeft(13);
        day1_6.setRoundTopRight(13);
        calendar.add(day1_6);

        day2_6.setBackground(new java.awt.Color(245, 245, 246));
        day2_6.setForeground(new java.awt.Color(0, 0, 0));
        day2_6.setBorderColor(java.awt.Color.darkGray);
        day2_6.setBorderPainted(true);
        day2_6.setName("day2_6"); // NOI18N
        day2_6.setRoundBottomLeft(13);
        day2_6.setRoundBottomRight(13);
        day2_6.setRoundTopLeft(13);
        day2_6.setRoundTopRight(13);
        calendar.add(day2_6);

        day3_6.setBackground(new java.awt.Color(245, 245, 246));
        day3_6.setForeground(new java.awt.Color(0, 0, 0));
        day3_6.setBorderColor(java.awt.Color.darkGray);
        day3_6.setBorderPainted(true);
        day3_6.setName("day3_6"); // NOI18N
        day3_6.setRoundBottomLeft(13);
        day3_6.setRoundBottomRight(13);
        day3_6.setRoundTopLeft(13);
        day3_6.setRoundTopRight(13);
        calendar.add(day3_6);

        day4_6.setBackground(new java.awt.Color(245, 245, 246));
        day4_6.setForeground(new java.awt.Color(0, 0, 0));
        day4_6.setBorderColor(java.awt.Color.darkGray);
        day4_6.setBorderPainted(true);
        day4_6.setName("day4_6"); // NOI18N
        day4_6.setRoundBottomLeft(13);
        day4_6.setRoundBottomRight(13);
        day4_6.setRoundTopLeft(13);
        day4_6.setRoundTopRight(13);
        calendar.add(day4_6);

        day5_6.setBackground(new java.awt.Color(245, 245, 246));
        day5_6.setForeground(new java.awt.Color(0, 0, 0));
        day5_6.setBorderColor(java.awt.Color.darkGray);
        day5_6.setBorderPainted(true);
        day5_6.setName("day5_6"); // NOI18N
        day5_6.setRoundBottomLeft(13);
        day5_6.setRoundBottomRight(13);
        day5_6.setRoundTopLeft(13);
        day5_6.setRoundTopRight(13);
        calendar.add(day5_6);

        day6_6.setBackground(new java.awt.Color(245, 245, 246));
        day6_6.setForeground(new java.awt.Color(0, 0, 0));
        day6_6.setBorderColor(java.awt.Color.darkGray);
        day6_6.setBorderPainted(true);
        day6_6.setName("day6_6"); // NOI18N
        day6_6.setRoundBottomLeft(13);
        day6_6.setRoundBottomRight(13);
        day6_6.setRoundTopLeft(13);
        day6_6.setRoundTopRight(13);
        calendar.add(day6_6);

        day0_7.setBackground(new java.awt.Color(245, 245, 246));
        day0_7.setForeground(new java.awt.Color(0, 0, 0));
        day0_7.setBorderColor(java.awt.Color.darkGray);
        day0_7.setBorderPainted(true);
        day0_7.setName("day0_7"); // NOI18N
        day0_7.setRoundBottomLeft(13);
        day0_7.setRoundBottomRight(13);
        day0_7.setRoundTopLeft(13);
        day0_7.setRoundTopRight(13);
        calendar.add(day0_7);

        day1_7.setBackground(new java.awt.Color(245, 245, 246));
        day1_7.setForeground(new java.awt.Color(0, 0, 0));
        day1_7.setBorderColor(java.awt.Color.darkGray);
        day1_7.setBorderPainted(true);
        day1_7.setName("day1_7"); // NOI18N
        day1_7.setRoundBottomLeft(13);
        day1_7.setRoundBottomRight(13);
        day1_7.setRoundTopLeft(13);
        day1_7.setRoundTopRight(13);
        calendar.add(day1_7);

        day2_7.setBackground(new java.awt.Color(245, 245, 246));
        day2_7.setForeground(new java.awt.Color(0, 0, 0));
        day2_7.setBorderColor(java.awt.Color.darkGray);
        day2_7.setBorderPainted(true);
        day2_7.setName("day2_7"); // NOI18N
        day2_7.setRoundBottomLeft(13);
        day2_7.setRoundBottomRight(13);
        day2_7.setRoundTopLeft(13);
        day2_7.setRoundTopRight(13);
        calendar.add(day2_7);

        day3_7.setBackground(new java.awt.Color(245, 245, 246));
        day3_7.setForeground(new java.awt.Color(0, 0, 0));
        day3_7.setBorderColor(java.awt.Color.darkGray);
        day3_7.setBorderPainted(true);
        day3_7.setName("day3_7"); // NOI18N
        day3_7.setRoundBottomLeft(13);
        day3_7.setRoundBottomRight(13);
        day3_7.setRoundTopLeft(13);
        day3_7.setRoundTopRight(13);
        calendar.add(day3_7);

        day4_7.setBackground(new java.awt.Color(245, 245, 246));
        day4_7.setForeground(new java.awt.Color(0, 0, 0));
        day4_7.setBorderColor(java.awt.Color.darkGray);
        day4_7.setBorderPainted(true);
        day4_7.setName("day4_7"); // NOI18N
        day4_7.setRoundBottomLeft(13);
        day4_7.setRoundBottomRight(13);
        day4_7.setRoundTopLeft(13);
        day4_7.setRoundTopRight(13);
        calendar.add(day4_7);

        day5_7.setBackground(new java.awt.Color(245, 245, 246));
        day5_7.setForeground(new java.awt.Color(0, 0, 0));
        day5_7.setBorderColor(java.awt.Color.darkGray);
        day5_7.setBorderPainted(true);
        day5_7.setName("day5_7"); // NOI18N
        day5_7.setRoundBottomLeft(13);
        day5_7.setRoundBottomRight(13);
        day5_7.setRoundTopLeft(13);
        day5_7.setRoundTopRight(13);
        calendar.add(day5_7);

        day6_7.setBackground(new java.awt.Color(245, 245, 246));
        day6_7.setForeground(new java.awt.Color(0, 0, 0));
        day6_7.setBorderColor(java.awt.Color.darkGray);
        day6_7.setBorderPainted(true);
        day6_7.setName("day6_7"); // NOI18N
        day6_7.setRoundBottomLeft(13);
        day6_7.setRoundBottomRight(13);
        day6_7.setRoundTopLeft(13);
        day6_7.setRoundTopRight(13);
        calendar.add(day6_7);

        day0_8.setBackground(new java.awt.Color(245, 245, 246));
        day0_8.setForeground(new java.awt.Color(0, 0, 0));
        day0_8.setBorderColor(java.awt.Color.darkGray);
        day0_8.setBorderPainted(true);
        day0_8.setName("day0_8"); // NOI18N
        day0_8.setRoundBottomLeft(13);
        day0_8.setRoundBottomRight(13);
        day0_8.setRoundTopLeft(13);
        day0_8.setRoundTopRight(13);
        calendar.add(day0_8);

        day1_8.setBackground(new java.awt.Color(245, 245, 246));
        day1_8.setForeground(new java.awt.Color(0, 0, 0));
        day1_8.setBorderColor(java.awt.Color.darkGray);
        day1_8.setBorderPainted(true);
        day1_8.setName("day1_8"); // NOI18N
        day1_8.setRoundBottomLeft(13);
        day1_8.setRoundBottomRight(13);
        day1_8.setRoundTopLeft(13);
        day1_8.setRoundTopRight(13);
        calendar.add(day1_8);

        day2_8.setBackground(new java.awt.Color(245, 245, 246));
        day2_8.setForeground(new java.awt.Color(0, 0, 0));
        day2_8.setBorderColor(java.awt.Color.darkGray);
        day2_8.setBorderPainted(true);
        day2_8.setName("day2_8"); // NOI18N
        day2_8.setRoundBottomLeft(13);
        day2_8.setRoundBottomRight(13);
        day2_8.setRoundTopLeft(13);
        day2_8.setRoundTopRight(13);
        calendar.add(day2_8);

        day3_8.setBackground(new java.awt.Color(245, 245, 246));
        day3_8.setForeground(new java.awt.Color(0, 0, 0));
        day3_8.setBorderColor(java.awt.Color.darkGray);
        day3_8.setBorderPainted(true);
        day3_8.setName("day3_8"); // NOI18N
        day3_8.setRoundBottomLeft(13);
        day3_8.setRoundBottomRight(13);
        day3_8.setRoundTopLeft(13);
        day3_8.setRoundTopRight(13);
        calendar.add(day3_8);

        day4_8.setBackground(new java.awt.Color(245, 245, 246));
        day4_8.setForeground(new java.awt.Color(0, 0, 0));
        day4_8.setBorderColor(java.awt.Color.darkGray);
        day4_8.setBorderPainted(true);
        day4_8.setName("day4_8"); // NOI18N
        day4_8.setRoundBottomLeft(13);
        day4_8.setRoundBottomRight(13);
        day4_8.setRoundTopLeft(13);
        day4_8.setRoundTopRight(13);
        calendar.add(day4_8);

        day5_8.setBackground(new java.awt.Color(245, 245, 246));
        day5_8.setForeground(new java.awt.Color(0, 0, 0));
        day5_8.setBorderColor(java.awt.Color.darkGray);
        day5_8.setBorderPainted(true);
        day5_8.setName("day5_8"); // NOI18N
        day5_8.setRoundBottomLeft(13);
        day5_8.setRoundBottomRight(13);
        day5_8.setRoundTopLeft(13);
        day5_8.setRoundTopRight(13);
        calendar.add(day5_8);

        day6_8.setBackground(new java.awt.Color(245, 245, 246));
        day6_8.setForeground(new java.awt.Color(0, 0, 0));
        day6_8.setBorderColor(java.awt.Color.darkGray);
        day6_8.setBorderPainted(true);
        day6_8.setName("day6_8"); // NOI18N
        day6_8.setRoundBottomLeft(13);
        day6_8.setRoundBottomRight(13);
        day6_8.setRoundTopLeft(13);
        day6_8.setRoundTopRight(13);
        calendar.add(day6_8);

        day0_9.setBackground(new java.awt.Color(245, 245, 246));
        day0_9.setForeground(new java.awt.Color(0, 0, 0));
        day0_9.setBorderColor(java.awt.Color.darkGray);
        day0_9.setBorderPainted(true);
        day0_9.setName("day0_9"); // NOI18N
        day0_9.setRoundBottomLeft(13);
        day0_9.setRoundBottomRight(13);
        day0_9.setRoundTopLeft(13);
        day0_9.setRoundTopRight(13);
        calendar.add(day0_9);

        day1_9.setBackground(new java.awt.Color(245, 245, 246));
        day1_9.setForeground(new java.awt.Color(0, 0, 0));
        day1_9.setBorderColor(java.awt.Color.darkGray);
        day1_9.setBorderPainted(true);
        day1_9.setName("day1_9"); // NOI18N
        day1_9.setRoundBottomLeft(13);
        day1_9.setRoundBottomRight(13);
        day1_9.setRoundTopLeft(13);
        day1_9.setRoundTopRight(13);
        calendar.add(day1_9);

        day2_9.setBackground(new java.awt.Color(245, 245, 246));
        day2_9.setForeground(new java.awt.Color(0, 0, 0));
        day2_9.setBorderColor(java.awt.Color.darkGray);
        day2_9.setBorderPainted(true);
        day2_9.setName("day2_9"); // NOI18N
        day2_9.setRoundBottomLeft(13);
        day2_9.setRoundBottomRight(13);
        day2_9.setRoundTopLeft(13);
        day2_9.setRoundTopRight(13);
        calendar.add(day2_9);

        day3_9.setBackground(new java.awt.Color(245, 245, 246));
        day3_9.setForeground(new java.awt.Color(0, 0, 0));
        day3_9.setBorderColor(java.awt.Color.darkGray);
        day3_9.setBorderPainted(true);
        day3_9.setName("day3_9"); // NOI18N
        day3_9.setRoundBottomLeft(13);
        day3_9.setRoundBottomRight(13);
        day3_9.setRoundTopLeft(13);
        day3_9.setRoundTopRight(13);
        calendar.add(day3_9);

        day4_9.setBackground(new java.awt.Color(245, 245, 246));
        day4_9.setForeground(new java.awt.Color(0, 0, 0));
        day4_9.setBorderColor(java.awt.Color.darkGray);
        day4_9.setBorderPainted(true);
        day4_9.setName("day4_9"); // NOI18N
        day4_9.setRoundBottomLeft(13);
        day4_9.setRoundBottomRight(13);
        day4_9.setRoundTopLeft(13);
        day4_9.setRoundTopRight(13);
        calendar.add(day4_9);

        day5_9.setBackground(new java.awt.Color(245, 245, 246));
        day5_9.setForeground(new java.awt.Color(0, 0, 0));
        day5_9.setBorderColor(java.awt.Color.darkGray);
        day5_9.setBorderPainted(true);
        day5_9.setName("day5_9"); // NOI18N
        day5_9.setRoundBottomLeft(13);
        day5_9.setRoundBottomRight(13);
        day5_9.setRoundTopLeft(13);
        day5_9.setRoundTopRight(13);
        calendar.add(day5_9);

        day6_9.setBackground(new java.awt.Color(245, 245, 246));
        day6_9.setForeground(new java.awt.Color(0, 0, 0));
        day6_9.setBorderColor(java.awt.Color.darkGray);
        day6_9.setBorderPainted(true);
        day6_9.setName("day6_9"); // NOI18N
        day6_9.setRoundBottomLeft(13);
        day6_9.setRoundBottomRight(13);
        day6_9.setRoundTopLeft(13);
        day6_9.setRoundTopRight(13);
        calendar.add(day6_9);

        day0_10.setBackground(new java.awt.Color(245, 245, 246));
        day0_10.setForeground(new java.awt.Color(0, 0, 0));
        day0_10.setBorderColor(java.awt.Color.darkGray);
        day0_10.setBorderPainted(true);
        day0_10.setName("day0_10"); // NOI18N
        day0_10.setRoundBottomLeft(13);
        day0_10.setRoundBottomRight(13);
        day0_10.setRoundTopLeft(13);
        day0_10.setRoundTopRight(13);
        calendar.add(day0_10);

        day1_10.setBackground(new java.awt.Color(245, 245, 246));
        day1_10.setForeground(new java.awt.Color(0, 0, 0));
        day1_10.setBorderColor(java.awt.Color.darkGray);
        day1_10.setBorderPainted(true);
        day1_10.setName("day1_10"); // NOI18N
        day1_10.setRoundBottomLeft(13);
        day1_10.setRoundBottomRight(13);
        day1_10.setRoundTopLeft(13);
        day1_10.setRoundTopRight(13);
        calendar.add(day1_10);

        day2_10.setBackground(new java.awt.Color(245, 245, 246));
        day2_10.setForeground(new java.awt.Color(0, 0, 0));
        day2_10.setBorderColor(java.awt.Color.darkGray);
        day2_10.setBorderPainted(true);
        day2_10.setName("day2_10"); // NOI18N
        day2_10.setRoundBottomLeft(13);
        day2_10.setRoundBottomRight(13);
        day2_10.setRoundTopLeft(13);
        day2_10.setRoundTopRight(13);
        calendar.add(day2_10);

        day3_10.setBackground(new java.awt.Color(245, 245, 246));
        day3_10.setForeground(new java.awt.Color(0, 0, 0));
        day3_10.setBorderColor(java.awt.Color.darkGray);
        day3_10.setBorderPainted(true);
        day3_10.setName("day3_10"); // NOI18N
        day3_10.setRoundBottomLeft(13);
        day3_10.setRoundBottomRight(13);
        day3_10.setRoundTopLeft(13);
        day3_10.setRoundTopRight(13);
        calendar.add(day3_10);

        day4_10.setBackground(new java.awt.Color(245, 245, 246));
        day4_10.setForeground(new java.awt.Color(0, 0, 0));
        day4_10.setBorderColor(java.awt.Color.darkGray);
        day4_10.setBorderPainted(true);
        day4_10.setName("day4_10"); // NOI18N
        day4_10.setRoundBottomLeft(13);
        day4_10.setRoundBottomRight(13);
        day4_10.setRoundTopLeft(13);
        day4_10.setRoundTopRight(13);
        calendar.add(day4_10);

        day5_10.setBackground(new java.awt.Color(245, 245, 246));
        day5_10.setForeground(new java.awt.Color(0, 0, 0));
        day5_10.setBorderColor(java.awt.Color.darkGray);
        day5_10.setBorderPainted(true);
        day5_10.setName("day5_10"); // NOI18N
        day5_10.setRoundBottomLeft(13);
        day5_10.setRoundBottomRight(13);
        day5_10.setRoundTopLeft(13);
        day5_10.setRoundTopRight(13);
        calendar.add(day5_10);

        day6_10.setBackground(new java.awt.Color(245, 245, 246));
        day6_10.setForeground(new java.awt.Color(0, 0, 0));
        day6_10.setBorderColor(java.awt.Color.darkGray);
        day6_10.setBorderPainted(true);
        day6_10.setName("day6_10"); // NOI18N
        day6_10.setRoundBottomLeft(13);
        day6_10.setRoundBottomRight(13);
        day6_10.setRoundTopLeft(13);
        day6_10.setRoundTopRight(13);
        calendar.add(day6_10);

        day0_11.setBackground(new java.awt.Color(245, 245, 246));
        day0_11.setForeground(new java.awt.Color(0, 0, 0));
        day0_11.setBorderColor(java.awt.Color.darkGray);
        day0_11.setBorderPainted(true);
        day0_11.setName("day0_11"); // NOI18N
        day0_11.setRoundBottomLeft(13);
        day0_11.setRoundBottomRight(13);
        day0_11.setRoundTopLeft(13);
        day0_11.setRoundTopRight(13);
        calendar.add(day0_11);

        day1_11.setBackground(new java.awt.Color(245, 245, 246));
        day1_11.setForeground(new java.awt.Color(0, 0, 0));
        day1_11.setBorderColor(java.awt.Color.darkGray);
        day1_11.setBorderPainted(true);
        day1_11.setName("day1_11"); // NOI18N
        day1_11.setRoundBottomLeft(13);
        day1_11.setRoundBottomRight(13);
        day1_11.setRoundTopLeft(13);
        day1_11.setRoundTopRight(13);
        calendar.add(day1_11);

        day2_11.setBackground(new java.awt.Color(245, 245, 246));
        day2_11.setForeground(new java.awt.Color(0, 0, 0));
        day2_11.setBorderColor(java.awt.Color.darkGray);
        day2_11.setBorderPainted(true);
        day2_11.setName("day2_11"); // NOI18N
        day2_11.setRoundBottomLeft(13);
        day2_11.setRoundBottomRight(13);
        day2_11.setRoundTopLeft(13);
        day2_11.setRoundTopRight(13);
        calendar.add(day2_11);

        day3_11.setBackground(new java.awt.Color(245, 245, 246));
        day3_11.setForeground(new java.awt.Color(0, 0, 0));
        day3_11.setBorderColor(java.awt.Color.darkGray);
        day3_11.setBorderPainted(true);
        day3_11.setName("day3_11"); // NOI18N
        day3_11.setRoundBottomLeft(13);
        day3_11.setRoundBottomRight(13);
        day3_11.setRoundTopLeft(13);
        day3_11.setRoundTopRight(13);
        calendar.add(day3_11);

        day4_11.setBackground(new java.awt.Color(245, 245, 246));
        day4_11.setForeground(new java.awt.Color(0, 0, 0));
        day4_11.setBorderColor(java.awt.Color.darkGray);
        day4_11.setBorderPainted(true);
        day4_11.setName("day4_11"); // NOI18N
        day4_11.setRoundBottomLeft(13);
        day4_11.setRoundBottomRight(13);
        day4_11.setRoundTopLeft(13);
        day4_11.setRoundTopRight(13);
        calendar.add(day4_11);

        day5_11.setBackground(new java.awt.Color(245, 245, 246));
        day5_11.setForeground(new java.awt.Color(0, 0, 0));
        day5_11.setBorderColor(java.awt.Color.darkGray);
        day5_11.setBorderPainted(true);
        day5_11.setName("day5_11"); // NOI18N
        day5_11.setRoundBottomLeft(13);
        day5_11.setRoundBottomRight(13);
        day5_11.setRoundTopLeft(13);
        day5_11.setRoundTopRight(13);
        calendar.add(day5_11);

        day6_11.setBackground(new java.awt.Color(245, 245, 246));
        day6_11.setForeground(new java.awt.Color(0, 0, 0));
        day6_11.setBorderColor(java.awt.Color.darkGray);
        day6_11.setBorderPainted(true);
        day6_11.setName("day6_11"); // NOI18N
        day6_11.setRoundBottomLeft(13);
        day6_11.setRoundBottomRight(13);
        day6_11.setRoundTopLeft(13);
        day6_11.setRoundTopRight(13);
        calendar.add(day6_11);

        day0_12.setBackground(new java.awt.Color(245, 245, 246));
        day0_12.setForeground(new java.awt.Color(0, 0, 0));
        day0_12.setBorderColor(java.awt.Color.darkGray);
        day0_12.setBorderPainted(true);
        day0_12.setName("day0_12"); // NOI18N
        day0_12.setRoundBottomLeft(13);
        day0_12.setRoundBottomRight(13);
        day0_12.setRoundTopLeft(13);
        day0_12.setRoundTopRight(13);
        calendar.add(day0_12);

        day1_12.setBackground(new java.awt.Color(245, 245, 246));
        day1_12.setForeground(new java.awt.Color(0, 0, 0));
        day1_12.setBorderColor(java.awt.Color.darkGray);
        day1_12.setBorderPainted(true);
        day1_12.setName("day1_12"); // NOI18N
        day1_12.setRoundBottomLeft(13);
        day1_12.setRoundBottomRight(13);
        day1_12.setRoundTopLeft(13);
        day1_12.setRoundTopRight(13);
        calendar.add(day1_12);

        day2_12.setBackground(new java.awt.Color(245, 245, 246));
        day2_12.setForeground(new java.awt.Color(0, 0, 0));
        day2_12.setBorderColor(java.awt.Color.darkGray);
        day2_12.setBorderPainted(true);
        day2_12.setName("day2_12"); // NOI18N
        day2_12.setRoundBottomLeft(13);
        day2_12.setRoundBottomRight(13);
        day2_12.setRoundTopLeft(13);
        day2_12.setRoundTopRight(13);
        calendar.add(day2_12);

        day3_12.setBackground(new java.awt.Color(245, 245, 246));
        day3_12.setForeground(new java.awt.Color(0, 0, 0));
        day3_12.setBorderColor(java.awt.Color.darkGray);
        day3_12.setBorderPainted(true);
        day3_12.setName("day3_12"); // NOI18N
        day3_12.setRoundBottomLeft(13);
        day3_12.setRoundBottomRight(13);
        day3_12.setRoundTopLeft(13);
        day3_12.setRoundTopRight(13);
        calendar.add(day3_12);

        day4_12.setBackground(new java.awt.Color(245, 245, 246));
        day4_12.setForeground(new java.awt.Color(0, 0, 0));
        day4_12.setBorderColor(java.awt.Color.darkGray);
        day4_12.setBorderPainted(true);
        day4_12.setName("day4_12"); // NOI18N
        day4_12.setRoundBottomLeft(13);
        day4_12.setRoundBottomRight(13);
        day4_12.setRoundTopLeft(13);
        day4_12.setRoundTopRight(13);
        calendar.add(day4_12);

        day5_12.setBackground(new java.awt.Color(245, 245, 246));
        day5_12.setForeground(new java.awt.Color(0, 0, 0));
        day5_12.setBorderColor(java.awt.Color.darkGray);
        day5_12.setBorderPainted(true);
        day5_12.setName("day5_12"); // NOI18N
        day5_12.setRoundBottomLeft(13);
        day5_12.setRoundBottomRight(13);
        day5_12.setRoundTopLeft(13);
        day5_12.setRoundTopRight(13);
        calendar.add(day5_12);

        day6_12.setBackground(new java.awt.Color(245, 245, 246));
        day6_12.setForeground(new java.awt.Color(0, 0, 0));
        day6_12.setBorderColor(java.awt.Color.darkGray);
        day6_12.setBorderPainted(true);
        day6_12.setName("day6_12"); // NOI18N
        day6_12.setRoundBottomLeft(13);
        day6_12.setRoundBottomRight(13);
        day6_12.setRoundTopLeft(13);
        day6_12.setRoundTopRight(13);
        calendar.add(day6_12);

        myReservationCalendar.add(calendar);
        calendar.setBounds(30, 100, 780, 428);

        calendarDate.setBackground(new java.awt.Color(255, 255, 255));
        calendarDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                calendarDateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        calendarDate.setLayout(new java.awt.GridLayout(1, 13, 3, 0));

        date0.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date0.setForeground(new java.awt.Color(51, 51, 51));
        date0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date0);

        date1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(51, 51, 51));
        date1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date1);

        date2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date2.setForeground(new java.awt.Color(51, 51, 51));
        date2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date2);

        date3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date3.setForeground(new java.awt.Color(51, 51, 51));
        date3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date3);

        date4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date4.setForeground(new java.awt.Color(51, 51, 51));
        date4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date4);

        date5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date5.setForeground(new java.awt.Color(51, 51, 51));
        date5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date5);

        date6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date6.setForeground(new java.awt.Color(51, 51, 51));
        date6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date6);

        myReservationCalendar.add(calendarDate);
        calendarDate.setBounds(30, 80, 780, 20);

        calendarTime.setBackground(new java.awt.Color(255, 255, 255));
        calendarTime.setLayout(new java.awt.GridLayout(13, 7, 0, 3));

        time0.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time0.setText("1");
        calendarTime.add(time0);

        time1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time1.setText("2");
        calendarTime.add(time1);

        time2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time2.setText("3");
        calendarTime.add(time2);

        time3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time3.setText("4");
        calendarTime.add(time3);

        time4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time4.setText("5");
        calendarTime.add(time4);

        time5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time5.setText("6");
        calendarTime.add(time5);

        time6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time6.setText("7");
        calendarTime.add(time6);

        time7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time7.setText("8");
        calendarTime.add(time7);

        time8.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time8.setText("9");
        calendarTime.add(time8);

        time9.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time9.setText("10");
        calendarTime.add(time9);

        time10.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time10.setText("11");
        calendarTime.add(time10);

        time11.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time11.setText("12");
        calendarTime.add(time11);

        time12.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time12.setText("13");
        calendarTime.add(time12);

        myReservationCalendar.add(calendarTime);
        calendarTime.setBounds(8, 100, 20, 428);

        main.add(myReservationCalendar);
        myReservationCalendar.setBounds(272, 6, 820, 535);

        add(main, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void calendarDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_calendarDateAncestorAdded
        java.time.LocalDate today = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("E/yyyy-MM-dd");

        JLabel[] dateLabels = { date0, date1, date2, date3, date4, date5, date6 };

        for (int i = 0; i < dateLabels.length; i++) {
            java.time.LocalDate date = today.plusDays(i);
            dateLabels[i].setText(date.format(formatter)); // 예: "수/2025-05-01"
        }
    }//GEN-LAST:event_calendarDateAncestorAdded

    private void myReservationListAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_myReservationListAncestorAdded

        // 개인의 예약 내용을 저장해서 불러온 뒤 버튼을 추가한다.
        
        // 버튼 혹은 패널 혹은 라벨을 생성해서 값을 넣은 후
        // myReservationList.add(컴포넌트) 방식으로 추가한다.
    }//GEN-LAST:event_myReservationListAncestorAdded

    private void managerMenuCurrentUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_managerMenuCurrentUserAncestorAdded
        Timer userCountTimer = new Timer(3000, e -> {
            int currentUserCount = new UserClientController().currentUserCounts().currentUserCount;
            managerMenuCurrentUser.setText(currentUserCount + " 명 접속중");
        });
        userCountTimer.start();
    }//GEN-LAST:event_managerMenuCurrentUserAncestorAdded

    private void commonMenuCurrentUserAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_commonMenuCurrentUserAncestorAdded
        Timer userCountTimer = new Timer(3000, e -> {
            int currentUserCount = new UserClientController().currentUserCounts().currentUserCount;
            commonMenuCurrentUser.setText(currentUserCount + " 명 접속중");
        });
        userCountTimer.start();
    }//GEN-LAST:event_commonMenuCurrentUserAncestorAdded

    public void addLogoutListener(ActionListener listener) {
        logoutButton.addActionListener(listener);
        logoutButton1.addActionListener(listener);
    }
    public void addReservationMenuListener(ActionListener listener) {
        LectureRoomReservationMenu.addActionListener(listener);
    }
    public void addMyReservationMenuListener(ActionListener listener) {
        myReservationMenu.addActionListener(listener);
    }
    public void addManagementMenuListener(ActionListener listener) {
        manegementMenu.addActionListener(listener);
    }
    public void addUserManagementListener(ActionListener listener) {
        userManagementButton.addActionListener(listener);
    }
    public void addReservationManagementListener(ActionListener listener) {
        reservationManagementButton.addActionListener(listener);
    }
    public void addCommonMenuListener(ActionListener listener) {
        commonMenu.addActionListener(listener);
    }
    public void replaceMainContent(JPanel northPanel, JPanel centerPanel) {
        removeAll();
        if (northPanel != null) add(northPanel, BorderLayout.NORTH);
        if (centerPanel != null) add(centerPanel, BorderLayout.CENTER);
        revalidate();
        repaint();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private deu.view.custom.ButtonRound LectureRoomReservationMenu;
    private deu.view.custom.TextFieldRound buildingField;
    private javax.swing.JLabel buildingLabel;
    private javax.swing.JPanel calendar;
    private javax.swing.JPanel calendarDate;
    private javax.swing.JPanel calendarTime;
    private deu.view.custom.ButtonRound cancelButton;
    private deu.view.custom.ButtonRound commonMenu;
    private javax.swing.JLabel commonMenuCurrentUser;
    private deu.view.custom.PanelRound concurrentUsers;
    private deu.view.custom.PanelRound concurrentUsers1;
    private javax.swing.JLabel date0;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private deu.view.custom.ButtonRound day0_0;
    private deu.view.custom.ButtonRound day0_1;
    private deu.view.custom.ButtonRound day0_10;
    private deu.view.custom.ButtonRound day0_11;
    private deu.view.custom.ButtonRound day0_12;
    private deu.view.custom.ButtonRound day0_2;
    private deu.view.custom.ButtonRound day0_3;
    private deu.view.custom.ButtonRound day0_4;
    private deu.view.custom.ButtonRound day0_5;
    private deu.view.custom.ButtonRound day0_6;
    private deu.view.custom.ButtonRound day0_7;
    private deu.view.custom.ButtonRound day0_8;
    private deu.view.custom.ButtonRound day0_9;
    private deu.view.custom.ButtonRound day1_0;
    private deu.view.custom.ButtonRound day1_1;
    private deu.view.custom.ButtonRound day1_10;
    private deu.view.custom.ButtonRound day1_11;
    private deu.view.custom.ButtonRound day1_12;
    private deu.view.custom.ButtonRound day1_2;
    private deu.view.custom.ButtonRound day1_3;
    private deu.view.custom.ButtonRound day1_4;
    private deu.view.custom.ButtonRound day1_5;
    private deu.view.custom.ButtonRound day1_6;
    private deu.view.custom.ButtonRound day1_7;
    private deu.view.custom.ButtonRound day1_8;
    private deu.view.custom.ButtonRound day1_9;
    private deu.view.custom.ButtonRound day2_0;
    private deu.view.custom.ButtonRound day2_1;
    private deu.view.custom.ButtonRound day2_10;
    private deu.view.custom.ButtonRound day2_11;
    private deu.view.custom.ButtonRound day2_12;
    private deu.view.custom.ButtonRound day2_2;
    private deu.view.custom.ButtonRound day2_3;
    private deu.view.custom.ButtonRound day2_4;
    private deu.view.custom.ButtonRound day2_5;
    private deu.view.custom.ButtonRound day2_6;
    private deu.view.custom.ButtonRound day2_7;
    private deu.view.custom.ButtonRound day2_8;
    private deu.view.custom.ButtonRound day2_9;
    private deu.view.custom.ButtonRound day3_0;
    private deu.view.custom.ButtonRound day3_1;
    private deu.view.custom.ButtonRound day3_10;
    private deu.view.custom.ButtonRound day3_11;
    private deu.view.custom.ButtonRound day3_12;
    private deu.view.custom.ButtonRound day3_2;
    private deu.view.custom.ButtonRound day3_3;
    private deu.view.custom.ButtonRound day3_4;
    private deu.view.custom.ButtonRound day3_5;
    private deu.view.custom.ButtonRound day3_6;
    private deu.view.custom.ButtonRound day3_7;
    private deu.view.custom.ButtonRound day3_8;
    private deu.view.custom.ButtonRound day3_9;
    private deu.view.custom.ButtonRound day4_0;
    private deu.view.custom.ButtonRound day4_1;
    private deu.view.custom.ButtonRound day4_10;
    private deu.view.custom.ButtonRound day4_11;
    private deu.view.custom.ButtonRound day4_12;
    private deu.view.custom.ButtonRound day4_2;
    private deu.view.custom.ButtonRound day4_3;
    private deu.view.custom.ButtonRound day4_4;
    private deu.view.custom.ButtonRound day4_5;
    private deu.view.custom.ButtonRound day4_6;
    private deu.view.custom.ButtonRound day4_7;
    private deu.view.custom.ButtonRound day4_8;
    private deu.view.custom.ButtonRound day4_9;
    private deu.view.custom.ButtonRound day5_0;
    private deu.view.custom.ButtonRound day5_1;
    private deu.view.custom.ButtonRound day5_10;
    private deu.view.custom.ButtonRound day5_11;
    private deu.view.custom.ButtonRound day5_12;
    private deu.view.custom.ButtonRound day5_2;
    private deu.view.custom.ButtonRound day5_3;
    private deu.view.custom.ButtonRound day5_4;
    private deu.view.custom.ButtonRound day5_5;
    private deu.view.custom.ButtonRound day5_6;
    private deu.view.custom.ButtonRound day5_7;
    private deu.view.custom.ButtonRound day5_8;
    private deu.view.custom.ButtonRound day5_9;
    private deu.view.custom.ButtonRound day6_0;
    private deu.view.custom.ButtonRound day6_1;
    private deu.view.custom.ButtonRound day6_10;
    private deu.view.custom.ButtonRound day6_11;
    private deu.view.custom.ButtonRound day6_12;
    private deu.view.custom.ButtonRound day6_2;
    private deu.view.custom.ButtonRound day6_3;
    private deu.view.custom.ButtonRound day6_4;
    private deu.view.custom.ButtonRound day6_5;
    private deu.view.custom.ButtonRound day6_6;
    private deu.view.custom.ButtonRound day6_7;
    private deu.view.custom.ButtonRound day6_8;
    private deu.view.custom.ButtonRound day6_9;
    private deu.view.custom.TextFieldRound descriptionField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JLabel deuLogo;
    private javax.swing.JLabel deuLogo1;
    private deu.view.custom.TextFieldRound floorField;
    private javax.swing.JLabel floorLabel;
    private deu.view.custom.TextFieldRound lectureRoomField;
    private javax.swing.JLabel lectureRoomLabel;
    private deu.view.custom.ButtonRound logoutButton;
    private deu.view.custom.ButtonRound logoutButton1;
    private javax.swing.JPanel main;
    private javax.swing.JPanel managerMenu;
    private javax.swing.JLabel managerMenuCurrentUser;
    private deu.view.custom.ButtonRound manegementMenu;
    private javax.swing.JPanel menu;
    private deu.view.custom.PanelRound myReservationCalendar;
    private javax.swing.JPanel myReservationList;
    private deu.view.custom.PanelRound myReservationListPanel;
    private deu.view.custom.ButtonRound myReservationMenu;
    private deu.view.custom.LabelRound profileImageField;
    private deu.view.custom.TextFieldRound profileNameField;
    private deu.view.custom.TextFieldRound profileNumberField;
    private deu.view.custom.PanelRound profilePanel;
    private javax.swing.JLabel reservationCount;
    private deu.view.custom.PanelRound reservationCountPanel;
    private javax.swing.JLabel reservationCountTitle;
    private deu.view.custom.PanelRound reservationInformationPanel;
    private deu.view.custom.ButtonRound reservationManagementButton;
    private javax.swing.JLabel reservationTotalCount;
    private deu.view.custom.PanelRound reservationTotalCountPanel;
    private javax.swing.JLabel reservationTotalCountTitle;
    private deu.view.custom.TextFieldRound reservationUserNumberField;
    private javax.swing.JLabel reservationUserNumberLabel;
    private javax.swing.JLabel time0;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time10;
    private javax.swing.JLabel time11;
    private javax.swing.JLabel time12;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JLabel time6;
    private javax.swing.JLabel time7;
    private javax.swing.JLabel time8;
    private javax.swing.JLabel time9;
    private deu.view.custom.TextFieldRound titleField;
    private javax.swing.JLabel titleLabel;
    private deu.view.custom.ButtonRound updateButton;
    private deu.view.custom.ButtonRound userManagementButton;

    public JPanel getMenuPanel() {
        return menu;
    }

    public JPanel getMainPanel() {
        return main;
    }

    public JPanel getManagerMenuPanel() {
        return managerMenu;
    }

    // End of variables declaration//GEN-END:variables
}
