/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package deu.view;

import deu.view.custom.ButtonRound;
import lombok.Getter;
import lombok.Setter;

import java.awt.Color;
import java.awt.Component;
import java.awt.Dimension;
import java.awt.event.ActionListener;
import java.awt.event.ItemListener;
import javax.swing.JButton;
import javax.swing.JLabel;

/**
 *
 * @author oxxultus
 */
@Getter
@Setter
public class ReservationManagement extends javax.swing.JPanel {
    
    // 선택시 버튼 색 저장하는 공간
    private JButton selectedCalendarButton = null;
    private JButton selectedRoomButton = null;
    private JButton selectedFloorButton = null;
    
    // 선택된 색상 저장
    public static final Color FLOOR_DEFAULT_COLOR = new Color(255, 255, 255);
    public static final Color FLOOR_SELECTED_COLOR = new Color(20, 90, 170);
    public static final Color ROOM_SELECTED_COLOR = new Color(20, 90, 170);

    /**
     * Creates new form Reservation
     */
    public ReservationManagement() {
        initComponents();
    }
    
    public ButtonRound createStyledButton(String text, int width, int height) {
        ButtonRound btn = new ButtonRound();
        btn.setText(text);
        btn.setPreferredSize(new Dimension(width, height));
        btn.setBackground(Color.WHITE);
        btn.setForeground(Color.BLACK);
        btn.setBorderColor(Color.GRAY);
        btn.setRoundTopLeft(10);
        btn.setRoundTopRight(10);
        btn.setRoundBottomLeft(10);
        btn.setRoundBottomRight(10);
        return btn;
    }
    public void clearSelectedButtons() {
        if (selectedFloorButton != null) {
            selectedFloorButton.setBackground(FLOOR_DEFAULT_COLOR);
            selectedFloorButton.setForeground(Color.BLACK);
            selectedFloorButton = null;
        }
        if (selectedRoomButton != null) {
            selectedRoomButton.setBackground(FLOOR_DEFAULT_COLOR);
            selectedRoomButton.setForeground(Color.BLACK);
            selectedRoomButton = null;
        }
        if (selectedCalendarButton != null) {
            selectedCalendarButton.setBackground(null);
            selectedCalendarButton = null;
        }
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buildingPanel = new deu.view.custom.PanelRound();
        buildingComboBox = new javax.swing.JComboBox<>();
        floorPanel = new deu.view.custom.PanelRound();
        floorDisplayPanel = new deu.view.custom.PanelRound();
        floorDisplayField = new javax.swing.JLabel();
        floorButtonPanel = new javax.swing.JPanel();
        lectureRoomListPanel = new deu.view.custom.PanelRound();
        lectureRoomList = new javax.swing.JPanel();
        myReservationCalendar = new deu.view.custom.PanelRound();
        reservationInformationPanel = new deu.view.custom.PanelRound();
        buildingLabel = new javax.swing.JLabel();
        buildingField = new deu.view.custom.TextFieldRound();
        floorLabel = new javax.swing.JLabel();
        floorField = new deu.view.custom.TextFieldRound();
        lectureRoomLabel = new javax.swing.JLabel();
        lectureRoomField = new deu.view.custom.TextFieldRound();
        titleLabel = new javax.swing.JLabel();
        titleField = new deu.view.custom.TextFieldRound();
        descriptionLabel = new javax.swing.JLabel();
        descriptionField = new deu.view.custom.TextFieldRound();
        reservationUserNumberLabel = new javax.swing.JLabel();
        reservationTimeField = new deu.view.custom.TextFieldRound();
        deleteButton = new deu.view.custom.ButtonRound();
        updateButton = new deu.view.custom.ButtonRound();
        titleLabel1 = new javax.swing.JLabel();
        titleField1 = new deu.view.custom.TextFieldRound();
        calendar = new javax.swing.JPanel();
        day0_0 = new deu.view.custom.ButtonRound();
        day1_0 = new deu.view.custom.ButtonRound();
        day2_0 = new deu.view.custom.ButtonRound();
        day3_0 = new deu.view.custom.ButtonRound();
        day4_0 = new deu.view.custom.ButtonRound();
        day5_0 = new deu.view.custom.ButtonRound();
        day6_0 = new deu.view.custom.ButtonRound();
        day0_1 = new deu.view.custom.ButtonRound();
        day1_1 = new deu.view.custom.ButtonRound();
        day2_1 = new deu.view.custom.ButtonRound();
        day3_1 = new deu.view.custom.ButtonRound();
        day4_1 = new deu.view.custom.ButtonRound();
        day5_1 = new deu.view.custom.ButtonRound();
        day6_1 = new deu.view.custom.ButtonRound();
        day0_2 = new deu.view.custom.ButtonRound();
        day1_2 = new deu.view.custom.ButtonRound();
        day2_2 = new deu.view.custom.ButtonRound();
        day3_2 = new deu.view.custom.ButtonRound();
        day4_2 = new deu.view.custom.ButtonRound();
        day5_2 = new deu.view.custom.ButtonRound();
        day6_2 = new deu.view.custom.ButtonRound();
        day0_3 = new deu.view.custom.ButtonRound();
        day1_3 = new deu.view.custom.ButtonRound();
        day2_3 = new deu.view.custom.ButtonRound();
        day3_3 = new deu.view.custom.ButtonRound();
        day4_3 = new deu.view.custom.ButtonRound();
        day5_3 = new deu.view.custom.ButtonRound();
        day6_3 = new deu.view.custom.ButtonRound();
        day0_4 = new deu.view.custom.ButtonRound();
        day1_4 = new deu.view.custom.ButtonRound();
        day2_4 = new deu.view.custom.ButtonRound();
        day3_4 = new deu.view.custom.ButtonRound();
        day4_4 = new deu.view.custom.ButtonRound();
        day5_4 = new deu.view.custom.ButtonRound();
        day6_4 = new deu.view.custom.ButtonRound();
        day0_5 = new deu.view.custom.ButtonRound();
        day1_5 = new deu.view.custom.ButtonRound();
        day2_5 = new deu.view.custom.ButtonRound();
        day3_5 = new deu.view.custom.ButtonRound();
        day4_5 = new deu.view.custom.ButtonRound();
        day5_5 = new deu.view.custom.ButtonRound();
        day6_5 = new deu.view.custom.ButtonRound();
        day0_6 = new deu.view.custom.ButtonRound();
        day1_6 = new deu.view.custom.ButtonRound();
        day2_6 = new deu.view.custom.ButtonRound();
        day3_6 = new deu.view.custom.ButtonRound();
        day4_6 = new deu.view.custom.ButtonRound();
        day5_6 = new deu.view.custom.ButtonRound();
        day6_6 = new deu.view.custom.ButtonRound();
        day0_7 = new deu.view.custom.ButtonRound();
        day1_7 = new deu.view.custom.ButtonRound();
        day2_7 = new deu.view.custom.ButtonRound();
        day3_7 = new deu.view.custom.ButtonRound();
        day4_7 = new deu.view.custom.ButtonRound();
        day5_7 = new deu.view.custom.ButtonRound();
        day6_7 = new deu.view.custom.ButtonRound();
        day0_8 = new deu.view.custom.ButtonRound();
        day1_8 = new deu.view.custom.ButtonRound();
        day2_8 = new deu.view.custom.ButtonRound();
        day3_8 = new deu.view.custom.ButtonRound();
        day4_8 = new deu.view.custom.ButtonRound();
        day5_8 = new deu.view.custom.ButtonRound();
        day6_8 = new deu.view.custom.ButtonRound();
        day0_9 = new deu.view.custom.ButtonRound();
        day1_9 = new deu.view.custom.ButtonRound();
        day2_9 = new deu.view.custom.ButtonRound();
        day3_9 = new deu.view.custom.ButtonRound();
        day4_9 = new deu.view.custom.ButtonRound();
        day5_9 = new deu.view.custom.ButtonRound();
        day6_9 = new deu.view.custom.ButtonRound();
        day0_10 = new deu.view.custom.ButtonRound();
        day1_10 = new deu.view.custom.ButtonRound();
        day2_10 = new deu.view.custom.ButtonRound();
        day3_10 = new deu.view.custom.ButtonRound();
        day4_10 = new deu.view.custom.ButtonRound();
        day5_10 = new deu.view.custom.ButtonRound();
        day6_10 = new deu.view.custom.ButtonRound();
        day0_11 = new deu.view.custom.ButtonRound();
        day1_11 = new deu.view.custom.ButtonRound();
        day2_11 = new deu.view.custom.ButtonRound();
        day3_11 = new deu.view.custom.ButtonRound();
        day4_11 = new deu.view.custom.ButtonRound();
        day5_11 = new deu.view.custom.ButtonRound();
        day6_11 = new deu.view.custom.ButtonRound();
        day0_12 = new deu.view.custom.ButtonRound();
        day1_12 = new deu.view.custom.ButtonRound();
        day2_12 = new deu.view.custom.ButtonRound();
        day3_12 = new deu.view.custom.ButtonRound();
        day4_12 = new deu.view.custom.ButtonRound();
        day5_12 = new deu.view.custom.ButtonRound();
        day6_12 = new deu.view.custom.ButtonRound();
        calendarDate = new javax.swing.JPanel();
        date0 = new javax.swing.JLabel();
        date1 = new javax.swing.JLabel();
        date2 = new javax.swing.JLabel();
        date3 = new javax.swing.JLabel();
        date4 = new javax.swing.JLabel();
        date5 = new javax.swing.JLabel();
        date6 = new javax.swing.JLabel();
        calendarTime = new javax.swing.JPanel();
        time0 = new javax.swing.JLabel();
        time1 = new javax.swing.JLabel();
        time2 = new javax.swing.JLabel();
        time3 = new javax.swing.JLabel();
        time4 = new javax.swing.JLabel();
        time5 = new javax.swing.JLabel();
        time6 = new javax.swing.JLabel();
        time7 = new javax.swing.JLabel();
        time8 = new javax.swing.JLabel();
        time9 = new javax.swing.JLabel();
        time10 = new javax.swing.JLabel();
        time11 = new javax.swing.JLabel();
        time12 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setMaximumSize(new java.awt.Dimension(1100, 550));
        setMinimumSize(new java.awt.Dimension(1100, 550));
        setLayout(null);

        buildingPanel.setBackground(new java.awt.Color(20, 90, 170));
        buildingPanel.setRoundBottomLeft(15);
        buildingPanel.setRoundBottomRight(15);
        buildingPanel.setRoundTopLeft(15);
        buildingPanel.setRoundTopRight(15);
        buildingPanel.setLayout(null);

        buildingComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "산학관", "정보관" }));
        buildingPanel.add(buildingComboBox);
        buildingComboBox.setBounds(10, 10, 220, 30);

        add(buildingPanel);
        buildingPanel.setBounds(6, 10, 240, 50);

        floorPanel.setBackground(new java.awt.Color(20, 90, 170));
        floorPanel.setRoundBottomLeft(15);
        floorPanel.setRoundBottomRight(15);
        floorPanel.setRoundTopLeft(15);
        floorPanel.setRoundTopRight(15);
        floorPanel.setLayout(null);

        floorDisplayPanel.setBackground(new java.awt.Color(51, 51, 51));
        floorDisplayPanel.setForeground(new java.awt.Color(60, 63, 65));
        floorDisplayPanel.setRoundBottomLeft(10);
        floorDisplayPanel.setRoundBottomRight(10);
        floorDisplayPanel.setRoundTopLeft(10);
        floorDisplayPanel.setRoundTopRight(10);
        floorDisplayPanel.setLayout(null);

        floorDisplayField.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        floorDisplayField.setForeground(new java.awt.Color(255, 255, 255));
        floorDisplayField.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorDisplayPanel.add(floorDisplayField);
        floorDisplayField.setBounds(0, 0, 60, 20);

        floorPanel.add(floorDisplayPanel);
        floorDisplayPanel.setBounds(90, 10, 60, 20);

        floorButtonPanel.setBackground(new java.awt.Color(20, 90, 170));
        floorButtonPanel.setLayout(new java.awt.GridLayout(3, 4, 5, 5));
        floorPanel.add(floorButtonPanel);
        floorButtonPanel.setBounds(10, 40, 220, 90);

        add(floorPanel);
        floorPanel.setBounds(6, 66, 240, 140);

        lectureRoomListPanel.setBackground(new java.awt.Color(255, 255, 255));
        lectureRoomListPanel.setForeground(new java.awt.Color(255, 255, 255));
        lectureRoomListPanel.setBorderColor(java.awt.Color.black);
        lectureRoomListPanel.setRoundBottomLeft(15);
        lectureRoomListPanel.setRoundBottomRight(15);
        lectureRoomListPanel.setRoundTopLeft(15);
        lectureRoomListPanel.setRoundTopRight(15);
        lectureRoomListPanel.setLayout(null);

        lectureRoomList.setBackground(new java.awt.Color(255, 255, 255));
        lectureRoomList.setLayout(new java.awt.GridLayout(6, 3, 5, 5));
        lectureRoomListPanel.add(lectureRoomList);
        lectureRoomList.setBounds(10, 10, 223, 300);

        add(lectureRoomListPanel);
        lectureRoomListPanel.setBounds(6, 220, 240, 320);

        myReservationCalendar.setBackground(new java.awt.Color(255, 255, 255));
        myReservationCalendar.setBorderColor(java.awt.Color.black);
        myReservationCalendar.setRoundBottomLeft(15);
        myReservationCalendar.setRoundBottomRight(15);
        myReservationCalendar.setRoundTopLeft(15);
        myReservationCalendar.setRoundTopRight(15);
        myReservationCalendar.setLayout(null);

        reservationInformationPanel.setBackground(new java.awt.Color(20, 90, 170));
        reservationInformationPanel.setRoundBottomLeft(10);
        reservationInformationPanel.setRoundBottomRight(10);
        reservationInformationPanel.setRoundTopLeft(10);
        reservationInformationPanel.setRoundTopRight(10);
        reservationInformationPanel.setLayout(null);

        buildingLabel.setForeground(new java.awt.Color(255, 255, 255));
        buildingLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        buildingLabel.setText("건물");
        reservationInformationPanel.add(buildingLabel);
        buildingLabel.setBounds(10, 10, 40, 20);

        buildingField.setEditable(false);
        buildingField.setBackground(new java.awt.Color(255, 255, 255));
        buildingField.setForeground(new java.awt.Color(0, 0, 0));
        buildingField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        buildingField.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        buildingField.setRound(10);
        reservationInformationPanel.add(buildingField);
        buildingField.setBounds(50, 10, 120, 20);

        floorLabel.setForeground(new java.awt.Color(255, 255, 255));
        floorLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        floorLabel.setText("층");
        reservationInformationPanel.add(floorLabel);
        floorLabel.setBounds(10, 40, 40, 20);

        floorField.setEditable(false);
        floorField.setBackground(new java.awt.Color(255, 255, 255));
        floorField.setForeground(new java.awt.Color(0, 0, 0));
        floorField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        floorField.setRound(10);
        reservationInformationPanel.add(floorField);
        floorField.setBounds(50, 40, 120, 20);

        lectureRoomLabel.setForeground(new java.awt.Color(255, 255, 255));
        lectureRoomLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lectureRoomLabel.setText("강의실");
        reservationInformationPanel.add(lectureRoomLabel);
        lectureRoomLabel.setBounds(180, 10, 40, 20);

        lectureRoomField.setEditable(false);
        lectureRoomField.setBackground(new java.awt.Color(255, 255, 255));
        lectureRoomField.setForeground(new java.awt.Color(0, 0, 0));
        lectureRoomField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lectureRoomField.setRound(10);
        reservationInformationPanel.add(lectureRoomField);
        lectureRoomField.setBounds(220, 10, 120, 20);

        titleLabel.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel.setText("제목");
        reservationInformationPanel.add(titleLabel);
        titleLabel.setBounds(350, 10, 40, 20);

        titleField.setBackground(new java.awt.Color(255, 255, 255));
        titleField.setForeground(new java.awt.Color(0, 0, 0));
        titleField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleField.setRound(10);
        reservationInformationPanel.add(titleField);
        titleField.setBounds(390, 10, 140, 20);

        descriptionLabel.setForeground(new java.awt.Color(255, 255, 255));
        descriptionLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriptionLabel.setText("설명");
        reservationInformationPanel.add(descriptionLabel);
        descriptionLabel.setBounds(350, 40, 40, 20);

        descriptionField.setBackground(new java.awt.Color(255, 255, 255));
        descriptionField.setForeground(new java.awt.Color(0, 0, 0));
        descriptionField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        descriptionField.setRound(10);
        reservationInformationPanel.add(descriptionField);
        descriptionField.setBounds(390, 40, 320, 20);

        reservationUserNumberLabel.setForeground(new java.awt.Color(255, 255, 255));
        reservationUserNumberLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        reservationUserNumberLabel.setText("시간");
        reservationInformationPanel.add(reservationUserNumberLabel);
        reservationUserNumberLabel.setBounds(180, 40, 40, 20);

        reservationTimeField.setEditable(false);
        reservationTimeField.setBackground(new java.awt.Color(255, 255, 255));
        reservationTimeField.setForeground(new java.awt.Color(0, 0, 0));
        reservationTimeField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        reservationTimeField.setCaretColor(new java.awt.Color(0, 0, 0));
        reservationTimeField.setFont(new java.awt.Font("Helvetica Neue", 0, 11)); // NOI18N
        reservationTimeField.setRound(10);
        reservationInformationPanel.add(reservationTimeField);
        reservationTimeField.setBounds(220, 40, 120, 20);

        deleteButton.setBackground(new java.awt.Color(102, 102, 102));
        deleteButton.setForeground(new java.awt.Color(255, 255, 255));
        deleteButton.setText("삭제하기");
        deleteButton.setBorderColor(null);
        deleteButton.setRoundBottomLeft(10);
        deleteButton.setRoundBottomRight(10);
        deleteButton.setRoundTopLeft(10);
        deleteButton.setRoundTopRight(10);
        reservationInformationPanel.add(deleteButton);
        deleteButton.setBounds(720, 40, 90, 23);

        updateButton.setBackground(new java.awt.Color(0, 102, 255));
        updateButton.setForeground(new java.awt.Color(255, 255, 255));
        updateButton.setText("수정하기");
        updateButton.setBorderColor(null);
        updateButton.setRoundBottomLeft(10);
        updateButton.setRoundBottomRight(10);
        updateButton.setRoundTopLeft(10);
        updateButton.setRoundTopRight(10);
        reservationInformationPanel.add(updateButton);
        updateButton.setBounds(720, 10, 90, 23);

        titleLabel1.setForeground(new java.awt.Color(255, 255, 255));
        titleLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titleLabel1.setText("예약자");
        reservationInformationPanel.add(titleLabel1);
        titleLabel1.setBounds(540, 10, 40, 20);

        titleField1.setEditable(false);
        titleField1.setBackground(new java.awt.Color(255, 255, 255));
        titleField1.setForeground(new java.awt.Color(0, 0, 0));
        titleField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        titleField1.setRound(10);
        reservationInformationPanel.add(titleField1);
        titleField1.setBounds(580, 10, 130, 20);

        myReservationCalendar.add(reservationInformationPanel);
        reservationInformationPanel.setBounds(10, 10, 820, 70);

        calendar.setBackground(new java.awt.Color(255, 255, 255));
        calendar.setLayout(new java.awt.GridLayout(13, 7, 3, 3));

        day0_0.setBackground(new java.awt.Color(245, 245, 246));
        day0_0.setForeground(new java.awt.Color(0, 0, 0));
        day0_0.setBorderColor(java.awt.Color.darkGray);
        day0_0.setBorderPainted(true);
        day0_0.setName("day0_0"); // NOI18N
        day0_0.setRoundBottomLeft(13);
        day0_0.setRoundBottomRight(13);
        day0_0.setRoundTopLeft(13);
        day0_0.setRoundTopRight(13);
        calendar.add(day0_0);

        day1_0.setBackground(new java.awt.Color(245, 245, 246));
        day1_0.setForeground(new java.awt.Color(0, 0, 0));
        day1_0.setBorderColor(java.awt.Color.darkGray);
        day1_0.setBorderPainted(true);
        day1_0.setName("day1_0"); // NOI18N
        day1_0.setRoundBottomLeft(13);
        day1_0.setRoundBottomRight(13);
        day1_0.setRoundTopLeft(13);
        day1_0.setRoundTopRight(13);
        calendar.add(day1_0);

        day2_0.setBackground(new java.awt.Color(245, 245, 246));
        day2_0.setForeground(new java.awt.Color(0, 0, 0));
        day2_0.setBorderColor(java.awt.Color.darkGray);
        day2_0.setBorderPainted(true);
        day2_0.setName("day2_0"); // NOI18N
        day2_0.setRoundBottomLeft(13);
        day2_0.setRoundBottomRight(13);
        day2_0.setRoundTopLeft(13);
        day2_0.setRoundTopRight(13);
        calendar.add(day2_0);

        day3_0.setBackground(new java.awt.Color(245, 245, 246));
        day3_0.setForeground(new java.awt.Color(0, 0, 0));
        day3_0.setBorderColor(java.awt.Color.darkGray);
        day3_0.setBorderPainted(true);
        day3_0.setName("day3_0"); // NOI18N
        day3_0.setRoundBottomLeft(13);
        day3_0.setRoundBottomRight(13);
        day3_0.setRoundTopLeft(13);
        day3_0.setRoundTopRight(13);
        calendar.add(day3_0);

        day4_0.setBackground(new java.awt.Color(245, 245, 246));
        day4_0.setForeground(new java.awt.Color(0, 0, 0));
        day4_0.setBorderColor(java.awt.Color.darkGray);
        day4_0.setBorderPainted(true);
        day4_0.setName("day4_0"); // NOI18N
        day4_0.setRoundBottomLeft(13);
        day4_0.setRoundBottomRight(13);
        day4_0.setRoundTopLeft(13);
        day4_0.setRoundTopRight(13);
        calendar.add(day4_0);

        day5_0.setBackground(new java.awt.Color(245, 245, 246));
        day5_0.setForeground(new java.awt.Color(0, 0, 0));
        day5_0.setBorderColor(java.awt.Color.darkGray);
        day5_0.setBorderPainted(true);
        day5_0.setName("day4_0"); // NOI18N
        day5_0.setRoundBottomLeft(13);
        day5_0.setRoundBottomRight(13);
        day5_0.setRoundTopLeft(13);
        day5_0.setRoundTopRight(13);
        calendar.add(day5_0);

        day6_0.setBackground(new java.awt.Color(245, 245, 246));
        day6_0.setForeground(new java.awt.Color(0, 0, 0));
        day6_0.setBorderColor(java.awt.Color.darkGray);
        day6_0.setBorderPainted(true);
        day6_0.setName("day6_0"); // NOI18N
        day6_0.setRoundBottomLeft(13);
        day6_0.setRoundBottomRight(13);
        day6_0.setRoundTopLeft(13);
        day6_0.setRoundTopRight(13);
        calendar.add(day6_0);

        day0_1.setBackground(new java.awt.Color(245, 245, 246));
        day0_1.setForeground(new java.awt.Color(0, 0, 0));
        day0_1.setBorderColor(java.awt.Color.darkGray);
        day0_1.setBorderPainted(true);
        day0_1.setName("day0_1"); // NOI18N
        day0_1.setRoundBottomLeft(13);
        day0_1.setRoundBottomRight(13);
        day0_1.setRoundTopLeft(13);
        day0_1.setRoundTopRight(13);
        calendar.add(day0_1);

        day1_1.setBackground(new java.awt.Color(245, 245, 246));
        day1_1.setForeground(new java.awt.Color(0, 0, 0));
        day1_1.setBorderColor(java.awt.Color.darkGray);
        day1_1.setBorderPainted(true);
        day1_1.setName("day1_1"); // NOI18N
        day1_1.setRoundBottomLeft(13);
        day1_1.setRoundBottomRight(13);
        day1_1.setRoundTopLeft(13);
        day1_1.setRoundTopRight(13);
        calendar.add(day1_1);

        day2_1.setBackground(new java.awt.Color(245, 245, 246));
        day2_1.setForeground(new java.awt.Color(0, 0, 0));
        day2_1.setBorderColor(java.awt.Color.darkGray);
        day2_1.setBorderPainted(true);
        day2_1.setName("day2_1"); // NOI18N
        day2_1.setRoundBottomLeft(13);
        day2_1.setRoundBottomRight(13);
        day2_1.setRoundTopLeft(13);
        day2_1.setRoundTopRight(13);
        calendar.add(day2_1);

        day3_1.setBackground(new java.awt.Color(245, 245, 246));
        day3_1.setForeground(new java.awt.Color(0, 0, 0));
        day3_1.setBorderColor(java.awt.Color.darkGray);
        day3_1.setBorderPainted(true);
        day3_1.setName("day3_1"); // NOI18N
        day3_1.setRoundBottomLeft(13);
        day3_1.setRoundBottomRight(13);
        day3_1.setRoundTopLeft(13);
        day3_1.setRoundTopRight(13);
        calendar.add(day3_1);

        day4_1.setBackground(new java.awt.Color(245, 245, 246));
        day4_1.setForeground(new java.awt.Color(0, 0, 0));
        day4_1.setBorderColor(java.awt.Color.darkGray);
        day4_1.setBorderPainted(true);
        day4_1.setName("day4_1"); // NOI18N
        day4_1.setRoundBottomLeft(13);
        day4_1.setRoundBottomRight(13);
        day4_1.setRoundTopLeft(13);
        day4_1.setRoundTopRight(13);
        calendar.add(day4_1);

        day5_1.setBackground(new java.awt.Color(245, 245, 246));
        day5_1.setForeground(new java.awt.Color(0, 0, 0));
        day5_1.setBorderColor(java.awt.Color.darkGray);
        day5_1.setBorderPainted(true);
        day5_1.setName("day5_1"); // NOI18N
        day5_1.setRoundBottomLeft(13);
        day5_1.setRoundBottomRight(13);
        day5_1.setRoundTopLeft(13);
        day5_1.setRoundTopRight(13);
        calendar.add(day5_1);

        day6_1.setBackground(new java.awt.Color(245, 245, 246));
        day6_1.setForeground(new java.awt.Color(0, 0, 0));
        day6_1.setBorderColor(java.awt.Color.darkGray);
        day6_1.setBorderPainted(true);
        day6_1.setName("day6_1"); // NOI18N
        day6_1.setRoundBottomLeft(13);
        day6_1.setRoundBottomRight(13);
        day6_1.setRoundTopLeft(13);
        day6_1.setRoundTopRight(13);
        calendar.add(day6_1);

        day0_2.setBackground(new java.awt.Color(245, 245, 246));
        day0_2.setForeground(new java.awt.Color(0, 0, 0));
        day0_2.setBorderColor(java.awt.Color.darkGray);
        day0_2.setBorderPainted(true);
        day0_2.setName("day0_2"); // NOI18N
        day0_2.setRoundBottomLeft(13);
        day0_2.setRoundBottomRight(13);
        day0_2.setRoundTopLeft(13);
        day0_2.setRoundTopRight(13);
        calendar.add(day0_2);

        day1_2.setBackground(new java.awt.Color(245, 245, 246));
        day1_2.setForeground(new java.awt.Color(0, 0, 0));
        day1_2.setBorderColor(java.awt.Color.darkGray);
        day1_2.setBorderPainted(true);
        day1_2.setName("day1_2"); // NOI18N
        day1_2.setRoundBottomLeft(13);
        day1_2.setRoundBottomRight(13);
        day1_2.setRoundTopLeft(13);
        day1_2.setRoundTopRight(13);
        calendar.add(day1_2);

        day2_2.setBackground(new java.awt.Color(245, 245, 246));
        day2_2.setForeground(new java.awt.Color(0, 0, 0));
        day2_2.setBorderColor(java.awt.Color.darkGray);
        day2_2.setBorderPainted(true);
        day2_2.setName("day2_2"); // NOI18N
        day2_2.setRoundBottomLeft(13);
        day2_2.setRoundBottomRight(13);
        day2_2.setRoundTopLeft(13);
        day2_2.setRoundTopRight(13);
        calendar.add(day2_2);

        day3_2.setBackground(new java.awt.Color(245, 245, 246));
        day3_2.setForeground(new java.awt.Color(0, 0, 0));
        day3_2.setBorderColor(java.awt.Color.darkGray);
        day3_2.setBorderPainted(true);
        day3_2.setName("day3_2"); // NOI18N
        day3_2.setRoundBottomLeft(13);
        day3_2.setRoundBottomRight(13);
        day3_2.setRoundTopLeft(13);
        day3_2.setRoundTopRight(13);
        calendar.add(day3_2);

        day4_2.setBackground(new java.awt.Color(245, 245, 246));
        day4_2.setForeground(new java.awt.Color(0, 0, 0));
        day4_2.setBorderColor(java.awt.Color.darkGray);
        day4_2.setBorderPainted(true);
        day4_2.setName("day4_2"); // NOI18N
        day4_2.setRoundBottomLeft(13);
        day4_2.setRoundBottomRight(13);
        day4_2.setRoundTopLeft(13);
        day4_2.setRoundTopRight(13);
        calendar.add(day4_2);

        day5_2.setBackground(new java.awt.Color(245, 245, 246));
        day5_2.setForeground(new java.awt.Color(0, 0, 0));
        day5_2.setBorderColor(java.awt.Color.darkGray);
        day5_2.setBorderPainted(true);
        day5_2.setName("day5_2"); // NOI18N
        day5_2.setRoundBottomLeft(13);
        day5_2.setRoundBottomRight(13);
        day5_2.setRoundTopLeft(13);
        day5_2.setRoundTopRight(13);
        calendar.add(day5_2);

        day6_2.setBackground(new java.awt.Color(245, 245, 246));
        day6_2.setForeground(new java.awt.Color(0, 0, 0));
        day6_2.setBorderColor(java.awt.Color.darkGray);
        day6_2.setBorderPainted(true);
        day6_2.setName("day6_2"); // NOI18N
        day6_2.setRoundBottomLeft(13);
        day6_2.setRoundBottomRight(13);
        day6_2.setRoundTopLeft(13);
        day6_2.setRoundTopRight(13);
        calendar.add(day6_2);

        day0_3.setBackground(new java.awt.Color(245, 245, 246));
        day0_3.setForeground(new java.awt.Color(0, 0, 0));
        day0_3.setBorderColor(java.awt.Color.darkGray);
        day0_3.setBorderPainted(true);
        day0_3.setName("day0_3"); // NOI18N
        day0_3.setRoundBottomLeft(13);
        day0_3.setRoundBottomRight(13);
        day0_3.setRoundTopLeft(13);
        day0_3.setRoundTopRight(13);
        calendar.add(day0_3);

        day1_3.setBackground(new java.awt.Color(245, 245, 246));
        day1_3.setForeground(new java.awt.Color(0, 0, 0));
        day1_3.setBorderColor(java.awt.Color.darkGray);
        day1_3.setBorderPainted(true);
        day1_3.setName("day1_3"); // NOI18N
        day1_3.setRoundBottomLeft(13);
        day1_3.setRoundBottomRight(13);
        day1_3.setRoundTopLeft(13);
        day1_3.setRoundTopRight(13);
        calendar.add(day1_3);

        day2_3.setBackground(new java.awt.Color(245, 245, 246));
        day2_3.setForeground(new java.awt.Color(0, 0, 0));
        day2_3.setBorderColor(java.awt.Color.darkGray);
        day2_3.setBorderPainted(true);
        day2_3.setName("day2_3"); // NOI18N
        day2_3.setRoundBottomLeft(13);
        day2_3.setRoundBottomRight(13);
        day2_3.setRoundTopLeft(13);
        day2_3.setRoundTopRight(13);
        calendar.add(day2_3);

        day3_3.setBackground(new java.awt.Color(245, 245, 246));
        day3_3.setForeground(new java.awt.Color(0, 0, 0));
        day3_3.setBorderColor(java.awt.Color.darkGray);
        day3_3.setBorderPainted(true);
        day3_3.setName("day3_3"); // NOI18N
        day3_3.setRoundBottomLeft(13);
        day3_3.setRoundBottomRight(13);
        day3_3.setRoundTopLeft(13);
        day3_3.setRoundTopRight(13);
        calendar.add(day3_3);

        day4_3.setBackground(new java.awt.Color(245, 245, 246));
        day4_3.setForeground(new java.awt.Color(0, 0, 0));
        day4_3.setBorderColor(java.awt.Color.darkGray);
        day4_3.setBorderPainted(true);
        day4_3.setName("day4_3"); // NOI18N
        day4_3.setRoundBottomLeft(13);
        day4_3.setRoundBottomRight(13);
        day4_3.setRoundTopLeft(13);
        day4_3.setRoundTopRight(13);
        calendar.add(day4_3);

        day5_3.setBackground(new java.awt.Color(245, 245, 246));
        day5_3.setForeground(new java.awt.Color(0, 0, 0));
        day5_3.setBorderColor(java.awt.Color.darkGray);
        day5_3.setBorderPainted(true);
        day5_3.setName("day5_3"); // NOI18N
        day5_3.setRoundBottomLeft(13);
        day5_3.setRoundBottomRight(13);
        day5_3.setRoundTopLeft(13);
        day5_3.setRoundTopRight(13);
        calendar.add(day5_3);

        day6_3.setBackground(new java.awt.Color(245, 245, 246));
        day6_3.setForeground(new java.awt.Color(0, 0, 0));
        day6_3.setBorderColor(java.awt.Color.darkGray);
        day6_3.setBorderPainted(true);
        day6_3.setName("day6_3"); // NOI18N
        day6_3.setRoundBottomLeft(13);
        day6_3.setRoundBottomRight(13);
        day6_3.setRoundTopLeft(13);
        day6_3.setRoundTopRight(13);
        calendar.add(day6_3);

        day0_4.setBackground(new java.awt.Color(245, 245, 246));
        day0_4.setForeground(new java.awt.Color(0, 0, 0));
        day0_4.setBorderColor(java.awt.Color.darkGray);
        day0_4.setBorderPainted(true);
        day0_4.setName("day0_4"); // NOI18N
        day0_4.setRoundBottomLeft(13);
        day0_4.setRoundBottomRight(13);
        day0_4.setRoundTopLeft(13);
        day0_4.setRoundTopRight(13);
        calendar.add(day0_4);

        day1_4.setBackground(new java.awt.Color(245, 245, 246));
        day1_4.setForeground(new java.awt.Color(0, 0, 0));
        day1_4.setBorderColor(java.awt.Color.darkGray);
        day1_4.setBorderPainted(true);
        day1_4.setName("day1_4"); // NOI18N
        day1_4.setRoundBottomLeft(13);
        day1_4.setRoundBottomRight(13);
        day1_4.setRoundTopLeft(13);
        day1_4.setRoundTopRight(13);
        calendar.add(day1_4);

        day2_4.setBackground(new java.awt.Color(245, 245, 246));
        day2_4.setForeground(new java.awt.Color(0, 0, 0));
        day2_4.setBorderColor(java.awt.Color.darkGray);
        day2_4.setBorderPainted(true);
        day2_4.setName("day2_4"); // NOI18N
        day2_4.setRoundBottomLeft(13);
        day2_4.setRoundBottomRight(13);
        day2_4.setRoundTopLeft(13);
        day2_4.setRoundTopRight(13);
        calendar.add(day2_4);

        day3_4.setBackground(new java.awt.Color(245, 245, 246));
        day3_4.setForeground(new java.awt.Color(0, 0, 0));
        day3_4.setBorderColor(java.awt.Color.darkGray);
        day3_4.setBorderPainted(true);
        day3_4.setName("day3_4"); // NOI18N
        day3_4.setRoundBottomLeft(13);
        day3_4.setRoundBottomRight(13);
        day3_4.setRoundTopLeft(13);
        day3_4.setRoundTopRight(13);
        calendar.add(day3_4);

        day4_4.setBackground(new java.awt.Color(245, 245, 246));
        day4_4.setForeground(new java.awt.Color(0, 0, 0));
        day4_4.setBorderColor(java.awt.Color.darkGray);
        day4_4.setBorderPainted(true);
        day4_4.setName("day4_4"); // NOI18N
        day4_4.setRoundBottomLeft(13);
        day4_4.setRoundBottomRight(13);
        day4_4.setRoundTopLeft(13);
        day4_4.setRoundTopRight(13);
        calendar.add(day4_4);

        day5_4.setBackground(new java.awt.Color(245, 245, 246));
        day5_4.setForeground(new java.awt.Color(0, 0, 0));
        day5_4.setBorderColor(java.awt.Color.darkGray);
        day5_4.setBorderPainted(true);
        day5_4.setName("day5_4"); // NOI18N
        day5_4.setRoundBottomLeft(13);
        day5_4.setRoundBottomRight(13);
        day5_4.setRoundTopLeft(13);
        day5_4.setRoundTopRight(13);
        calendar.add(day5_4);

        day6_4.setBackground(new java.awt.Color(245, 245, 246));
        day6_4.setForeground(new java.awt.Color(0, 0, 0));
        day6_4.setBorderColor(java.awt.Color.darkGray);
        day6_4.setBorderPainted(true);
        day6_4.setName("day6_4"); // NOI18N
        day6_4.setRoundBottomLeft(13);
        day6_4.setRoundBottomRight(13);
        day6_4.setRoundTopLeft(13);
        day6_4.setRoundTopRight(13);
        calendar.add(day6_4);

        day0_5.setBackground(new java.awt.Color(245, 245, 246));
        day0_5.setForeground(new java.awt.Color(0, 0, 0));
        day0_5.setBorderColor(java.awt.Color.darkGray);
        day0_5.setBorderPainted(true);
        day0_5.setName("day0_5"); // NOI18N
        day0_5.setRoundBottomLeft(13);
        day0_5.setRoundBottomRight(13);
        day0_5.setRoundTopLeft(13);
        day0_5.setRoundTopRight(13);
        calendar.add(day0_5);

        day1_5.setBackground(new java.awt.Color(245, 245, 246));
        day1_5.setForeground(new java.awt.Color(0, 0, 0));
        day1_5.setBorderColor(java.awt.Color.darkGray);
        day1_5.setBorderPainted(true);
        day1_5.setName("day1_5"); // NOI18N
        day1_5.setRoundBottomLeft(13);
        day1_5.setRoundBottomRight(13);
        day1_5.setRoundTopLeft(13);
        day1_5.setRoundTopRight(13);
        calendar.add(day1_5);

        day2_5.setBackground(new java.awt.Color(245, 245, 246));
        day2_5.setForeground(new java.awt.Color(0, 0, 0));
        day2_5.setBorderColor(java.awt.Color.darkGray);
        day2_5.setBorderPainted(true);
        day2_5.setName("day2_5"); // NOI18N
        day2_5.setRoundBottomLeft(13);
        day2_5.setRoundBottomRight(13);
        day2_5.setRoundTopLeft(13);
        day2_5.setRoundTopRight(13);
        calendar.add(day2_5);

        day3_5.setBackground(new java.awt.Color(245, 245, 246));
        day3_5.setForeground(new java.awt.Color(0, 0, 0));
        day3_5.setBorderColor(java.awt.Color.darkGray);
        day3_5.setBorderPainted(true);
        day3_5.setName("day3_5"); // NOI18N
        day3_5.setRoundBottomLeft(13);
        day3_5.setRoundBottomRight(13);
        day3_5.setRoundTopLeft(13);
        day3_5.setRoundTopRight(13);
        calendar.add(day3_5);

        day4_5.setBackground(new java.awt.Color(245, 245, 246));
        day4_5.setForeground(new java.awt.Color(0, 0, 0));
        day4_5.setBorderColor(java.awt.Color.darkGray);
        day4_5.setBorderPainted(true);
        day4_5.setName("day4_5"); // NOI18N
        day4_5.setRoundBottomLeft(13);
        day4_5.setRoundBottomRight(13);
        day4_5.setRoundTopLeft(13);
        day4_5.setRoundTopRight(13);
        calendar.add(day4_5);

        day5_5.setBackground(new java.awt.Color(245, 245, 246));
        day5_5.setForeground(new java.awt.Color(0, 0, 0));
        day5_5.setBorderColor(java.awt.Color.darkGray);
        day5_5.setBorderPainted(true);
        day5_5.setName("day5_5"); // NOI18N
        day5_5.setRoundBottomLeft(13);
        day5_5.setRoundBottomRight(13);
        day5_5.setRoundTopLeft(13);
        day5_5.setRoundTopRight(13);
        calendar.add(day5_5);

        day6_5.setBackground(new java.awt.Color(245, 245, 246));
        day6_5.setForeground(new java.awt.Color(0, 0, 0));
        day6_5.setBorderColor(java.awt.Color.darkGray);
        day6_5.setBorderPainted(true);
        day6_5.setName("day6_5"); // NOI18N
        day6_5.setRoundBottomLeft(13);
        day6_5.setRoundBottomRight(13);
        day6_5.setRoundTopLeft(13);
        day6_5.setRoundTopRight(13);
        calendar.add(day6_5);

        day0_6.setBackground(new java.awt.Color(245, 245, 246));
        day0_6.setForeground(new java.awt.Color(0, 0, 0));
        day0_6.setBorderColor(java.awt.Color.darkGray);
        day0_6.setBorderPainted(true);
        day0_6.setName("day0_6"); // NOI18N
        day0_6.setOpaque(true);
        day0_6.setRoundBottomLeft(13);
        day0_6.setRoundBottomRight(13);
        day0_6.setRoundTopLeft(13);
        day0_6.setRoundTopRight(13);
        calendar.add(day0_6);

        day1_6.setBackground(new java.awt.Color(245, 245, 246));
        day1_6.setForeground(new java.awt.Color(0, 0, 0));
        day1_6.setBorderColor(java.awt.Color.darkGray);
        day1_6.setBorderPainted(true);
        day1_6.setName("day1_6"); // NOI18N
        day1_6.setRoundBottomLeft(13);
        day1_6.setRoundBottomRight(13);
        day1_6.setRoundTopLeft(13);
        day1_6.setRoundTopRight(13);
        calendar.add(day1_6);

        day2_6.setBackground(new java.awt.Color(245, 245, 246));
        day2_6.setForeground(new java.awt.Color(0, 0, 0));
        day2_6.setBorderColor(java.awt.Color.darkGray);
        day2_6.setBorderPainted(true);
        day2_6.setName("day2_6"); // NOI18N
        day2_6.setRoundBottomLeft(13);
        day2_6.setRoundBottomRight(13);
        day2_6.setRoundTopLeft(13);
        day2_6.setRoundTopRight(13);
        calendar.add(day2_6);

        day3_6.setBackground(new java.awt.Color(245, 245, 246));
        day3_6.setForeground(new java.awt.Color(0, 0, 0));
        day3_6.setBorderColor(java.awt.Color.darkGray);
        day3_6.setBorderPainted(true);
        day3_6.setName("day3_6"); // NOI18N
        day3_6.setRoundBottomLeft(13);
        day3_6.setRoundBottomRight(13);
        day3_6.setRoundTopLeft(13);
        day3_6.setRoundTopRight(13);
        calendar.add(day3_6);

        day4_6.setBackground(new java.awt.Color(245, 245, 246));
        day4_6.setForeground(new java.awt.Color(0, 0, 0));
        day4_6.setBorderColor(java.awt.Color.darkGray);
        day4_6.setBorderPainted(true);
        day4_6.setName("day4_6"); // NOI18N
        day4_6.setRoundBottomLeft(13);
        day4_6.setRoundBottomRight(13);
        day4_6.setRoundTopLeft(13);
        day4_6.setRoundTopRight(13);
        calendar.add(day4_6);

        day5_6.setBackground(new java.awt.Color(245, 245, 246));
        day5_6.setForeground(new java.awt.Color(0, 0, 0));
        day5_6.setBorderColor(java.awt.Color.darkGray);
        day5_6.setBorderPainted(true);
        day5_6.setName("day5_6"); // NOI18N
        day5_6.setRoundBottomLeft(13);
        day5_6.setRoundBottomRight(13);
        day5_6.setRoundTopLeft(13);
        day5_6.setRoundTopRight(13);
        calendar.add(day5_6);

        day6_6.setBackground(new java.awt.Color(245, 245, 246));
        day6_6.setForeground(new java.awt.Color(0, 0, 0));
        day6_6.setBorderColor(java.awt.Color.darkGray);
        day6_6.setBorderPainted(true);
        day6_6.setName("day6_6"); // NOI18N
        day6_6.setRoundBottomLeft(13);
        day6_6.setRoundBottomRight(13);
        day6_6.setRoundTopLeft(13);
        day6_6.setRoundTopRight(13);
        calendar.add(day6_6);

        day0_7.setBackground(new java.awt.Color(245, 245, 246));
        day0_7.setForeground(new java.awt.Color(0, 0, 0));
        day0_7.setBorderColor(java.awt.Color.darkGray);
        day0_7.setBorderPainted(true);
        day0_7.setName("day0_7"); // NOI18N
        day0_7.setRoundBottomLeft(13);
        day0_7.setRoundBottomRight(13);
        day0_7.setRoundTopLeft(13);
        day0_7.setRoundTopRight(13);
        calendar.add(day0_7);

        day1_7.setBackground(new java.awt.Color(245, 245, 246));
        day1_7.setForeground(new java.awt.Color(0, 0, 0));
        day1_7.setBorderColor(java.awt.Color.darkGray);
        day1_7.setBorderPainted(true);
        day1_7.setName("day1_7"); // NOI18N
        day1_7.setRoundBottomLeft(13);
        day1_7.setRoundBottomRight(13);
        day1_7.setRoundTopLeft(13);
        day1_7.setRoundTopRight(13);
        calendar.add(day1_7);

        day2_7.setBackground(new java.awt.Color(245, 245, 246));
        day2_7.setForeground(new java.awt.Color(0, 0, 0));
        day2_7.setBorderColor(java.awt.Color.darkGray);
        day2_7.setBorderPainted(true);
        day2_7.setName("day2_7"); // NOI18N
        day2_7.setRoundBottomLeft(13);
        day2_7.setRoundBottomRight(13);
        day2_7.setRoundTopLeft(13);
        day2_7.setRoundTopRight(13);
        calendar.add(day2_7);

        day3_7.setBackground(new java.awt.Color(245, 245, 246));
        day3_7.setForeground(new java.awt.Color(0, 0, 0));
        day3_7.setBorderColor(java.awt.Color.darkGray);
        day3_7.setBorderPainted(true);
        day3_7.setName("day3_7"); // NOI18N
        day3_7.setRoundBottomLeft(13);
        day3_7.setRoundBottomRight(13);
        day3_7.setRoundTopLeft(13);
        day3_7.setRoundTopRight(13);
        calendar.add(day3_7);

        day4_7.setBackground(new java.awt.Color(245, 245, 246));
        day4_7.setForeground(new java.awt.Color(0, 0, 0));
        day4_7.setBorderColor(java.awt.Color.darkGray);
        day4_7.setBorderPainted(true);
        day4_7.setName("day4_7"); // NOI18N
        day4_7.setRoundBottomLeft(13);
        day4_7.setRoundBottomRight(13);
        day4_7.setRoundTopLeft(13);
        day4_7.setRoundTopRight(13);
        calendar.add(day4_7);

        day5_7.setBackground(new java.awt.Color(245, 245, 246));
        day5_7.setForeground(new java.awt.Color(0, 0, 0));
        day5_7.setBorderColor(java.awt.Color.darkGray);
        day5_7.setBorderPainted(true);
        day5_7.setName("day5_7"); // NOI18N
        day5_7.setRoundBottomLeft(13);
        day5_7.setRoundBottomRight(13);
        day5_7.setRoundTopLeft(13);
        day5_7.setRoundTopRight(13);
        calendar.add(day5_7);

        day6_7.setBackground(new java.awt.Color(245, 245, 246));
        day6_7.setForeground(new java.awt.Color(0, 0, 0));
        day6_7.setBorderColor(java.awt.Color.darkGray);
        day6_7.setBorderPainted(true);
        day6_7.setName("day6_7"); // NOI18N
        day6_7.setRoundBottomLeft(13);
        day6_7.setRoundBottomRight(13);
        day6_7.setRoundTopLeft(13);
        day6_7.setRoundTopRight(13);
        calendar.add(day6_7);

        day0_8.setBackground(new java.awt.Color(245, 245, 246));
        day0_8.setForeground(new java.awt.Color(0, 0, 0));
        day0_8.setBorderColor(java.awt.Color.darkGray);
        day0_8.setBorderPainted(true);
        day0_8.setName("day0_8"); // NOI18N
        day0_8.setRoundBottomLeft(13);
        day0_8.setRoundBottomRight(13);
        day0_8.setRoundTopLeft(13);
        day0_8.setRoundTopRight(13);
        calendar.add(day0_8);

        day1_8.setBackground(new java.awt.Color(245, 245, 246));
        day1_8.setForeground(new java.awt.Color(0, 0, 0));
        day1_8.setBorderColor(java.awt.Color.darkGray);
        day1_8.setBorderPainted(true);
        day1_8.setName("day1_8"); // NOI18N
        day1_8.setRoundBottomLeft(13);
        day1_8.setRoundBottomRight(13);
        day1_8.setRoundTopLeft(13);
        day1_8.setRoundTopRight(13);
        calendar.add(day1_8);

        day2_8.setBackground(new java.awt.Color(245, 245, 246));
        day2_8.setForeground(new java.awt.Color(0, 0, 0));
        day2_8.setBorderColor(java.awt.Color.darkGray);
        day2_8.setBorderPainted(true);
        day2_8.setName("day2_8"); // NOI18N
        day2_8.setRoundBottomLeft(13);
        day2_8.setRoundBottomRight(13);
        day2_8.setRoundTopLeft(13);
        day2_8.setRoundTopRight(13);
        calendar.add(day2_8);

        day3_8.setBackground(new java.awt.Color(245, 245, 246));
        day3_8.setForeground(new java.awt.Color(0, 0, 0));
        day3_8.setBorderColor(java.awt.Color.darkGray);
        day3_8.setBorderPainted(true);
        day3_8.setName("day3_8"); // NOI18N
        day3_8.setRoundBottomLeft(13);
        day3_8.setRoundBottomRight(13);
        day3_8.setRoundTopLeft(13);
        day3_8.setRoundTopRight(13);
        calendar.add(day3_8);

        day4_8.setBackground(new java.awt.Color(245, 245, 246));
        day4_8.setForeground(new java.awt.Color(0, 0, 0));
        day4_8.setBorderColor(java.awt.Color.darkGray);
        day4_8.setBorderPainted(true);
        day4_8.setName("day4_8"); // NOI18N
        day4_8.setRoundBottomLeft(13);
        day4_8.setRoundBottomRight(13);
        day4_8.setRoundTopLeft(13);
        day4_8.setRoundTopRight(13);
        calendar.add(day4_8);

        day5_8.setBackground(new java.awt.Color(245, 245, 246));
        day5_8.setForeground(new java.awt.Color(0, 0, 0));
        day5_8.setBorderColor(java.awt.Color.darkGray);
        day5_8.setBorderPainted(true);
        day5_8.setName("day5_8"); // NOI18N
        day5_8.setRoundBottomLeft(13);
        day5_8.setRoundBottomRight(13);
        day5_8.setRoundTopLeft(13);
        day5_8.setRoundTopRight(13);
        calendar.add(day5_8);

        day6_8.setBackground(new java.awt.Color(245, 245, 246));
        day6_8.setForeground(new java.awt.Color(0, 0, 0));
        day6_8.setBorderColor(java.awt.Color.darkGray);
        day6_8.setBorderPainted(true);
        day6_8.setName("day6_8"); // NOI18N
        day6_8.setRoundBottomLeft(13);
        day6_8.setRoundBottomRight(13);
        day6_8.setRoundTopLeft(13);
        day6_8.setRoundTopRight(13);
        calendar.add(day6_8);

        day0_9.setBackground(new java.awt.Color(245, 245, 246));
        day0_9.setForeground(new java.awt.Color(0, 0, 0));
        day0_9.setBorderColor(java.awt.Color.darkGray);
        day0_9.setBorderPainted(true);
        day0_9.setName("day0_9"); // NOI18N
        day0_9.setRoundBottomLeft(13);
        day0_9.setRoundBottomRight(13);
        day0_9.setRoundTopLeft(13);
        day0_9.setRoundTopRight(13);
        calendar.add(day0_9);

        day1_9.setBackground(new java.awt.Color(245, 245, 246));
        day1_9.setForeground(new java.awt.Color(0, 0, 0));
        day1_9.setBorderColor(java.awt.Color.darkGray);
        day1_9.setBorderPainted(true);
        day1_9.setName("day1_9"); // NOI18N
        day1_9.setRoundBottomLeft(13);
        day1_9.setRoundBottomRight(13);
        day1_9.setRoundTopLeft(13);
        day1_9.setRoundTopRight(13);
        calendar.add(day1_9);

        day2_9.setBackground(new java.awt.Color(245, 245, 246));
        day2_9.setForeground(new java.awt.Color(0, 0, 0));
        day2_9.setBorderColor(java.awt.Color.darkGray);
        day2_9.setBorderPainted(true);
        day2_9.setName("day2_9"); // NOI18N
        day2_9.setRoundBottomLeft(13);
        day2_9.setRoundBottomRight(13);
        day2_9.setRoundTopLeft(13);
        day2_9.setRoundTopRight(13);
        calendar.add(day2_9);

        day3_9.setBackground(new java.awt.Color(245, 245, 246));
        day3_9.setForeground(new java.awt.Color(0, 0, 0));
        day3_9.setBorderColor(java.awt.Color.darkGray);
        day3_9.setBorderPainted(true);
        day3_9.setName("day3_9"); // NOI18N
        day3_9.setRoundBottomLeft(13);
        day3_9.setRoundBottomRight(13);
        day3_9.setRoundTopLeft(13);
        day3_9.setRoundTopRight(13);
        calendar.add(day3_9);

        day4_9.setBackground(new java.awt.Color(245, 245, 246));
        day4_9.setForeground(new java.awt.Color(0, 0, 0));
        day4_9.setBorderColor(java.awt.Color.darkGray);
        day4_9.setBorderPainted(true);
        day4_9.setName("day4_9"); // NOI18N
        day4_9.setRoundBottomLeft(13);
        day4_9.setRoundBottomRight(13);
        day4_9.setRoundTopLeft(13);
        day4_9.setRoundTopRight(13);
        calendar.add(day4_9);

        day5_9.setBackground(new java.awt.Color(245, 245, 246));
        day5_9.setForeground(new java.awt.Color(0, 0, 0));
        day5_9.setBorderColor(java.awt.Color.darkGray);
        day5_9.setBorderPainted(true);
        day5_9.setName("day5_9"); // NOI18N
        day5_9.setRoundBottomLeft(13);
        day5_9.setRoundBottomRight(13);
        day5_9.setRoundTopLeft(13);
        day5_9.setRoundTopRight(13);
        calendar.add(day5_9);

        day6_9.setBackground(new java.awt.Color(245, 245, 246));
        day6_9.setForeground(new java.awt.Color(0, 0, 0));
        day6_9.setBorderColor(java.awt.Color.darkGray);
        day6_9.setBorderPainted(true);
        day6_9.setName("day6_9"); // NOI18N
        day6_9.setRoundBottomLeft(13);
        day6_9.setRoundBottomRight(13);
        day6_9.setRoundTopLeft(13);
        day6_9.setRoundTopRight(13);
        calendar.add(day6_9);

        day0_10.setBackground(new java.awt.Color(245, 245, 246));
        day0_10.setForeground(new java.awt.Color(0, 0, 0));
        day0_10.setBorderColor(java.awt.Color.darkGray);
        day0_10.setBorderPainted(true);
        day0_10.setName("day0_10"); // NOI18N
        day0_10.setRoundBottomLeft(13);
        day0_10.setRoundBottomRight(13);
        day0_10.setRoundTopLeft(13);
        day0_10.setRoundTopRight(13);
        calendar.add(day0_10);

        day1_10.setBackground(new java.awt.Color(245, 245, 246));
        day1_10.setForeground(new java.awt.Color(0, 0, 0));
        day1_10.setBorderColor(java.awt.Color.darkGray);
        day1_10.setBorderPainted(true);
        day1_10.setName("day1_10"); // NOI18N
        day1_10.setRoundBottomLeft(13);
        day1_10.setRoundBottomRight(13);
        day1_10.setRoundTopLeft(13);
        day1_10.setRoundTopRight(13);
        calendar.add(day1_10);

        day2_10.setBackground(new java.awt.Color(245, 245, 246));
        day2_10.setForeground(new java.awt.Color(0, 0, 0));
        day2_10.setBorderColor(java.awt.Color.darkGray);
        day2_10.setBorderPainted(true);
        day2_10.setName("day2_10"); // NOI18N
        day2_10.setRoundBottomLeft(13);
        day2_10.setRoundBottomRight(13);
        day2_10.setRoundTopLeft(13);
        day2_10.setRoundTopRight(13);
        calendar.add(day2_10);

        day3_10.setBackground(new java.awt.Color(245, 245, 246));
        day3_10.setForeground(new java.awt.Color(0, 0, 0));
        day3_10.setBorderColor(java.awt.Color.darkGray);
        day3_10.setBorderPainted(true);
        day3_10.setName("day3_10"); // NOI18N
        day3_10.setRoundBottomLeft(13);
        day3_10.setRoundBottomRight(13);
        day3_10.setRoundTopLeft(13);
        day3_10.setRoundTopRight(13);
        calendar.add(day3_10);

        day4_10.setBackground(new java.awt.Color(245, 245, 246));
        day4_10.setForeground(new java.awt.Color(0, 0, 0));
        day4_10.setBorderColor(java.awt.Color.darkGray);
        day4_10.setBorderPainted(true);
        day4_10.setName("day4_10"); // NOI18N
        day4_10.setRoundBottomLeft(13);
        day4_10.setRoundBottomRight(13);
        day4_10.setRoundTopLeft(13);
        day4_10.setRoundTopRight(13);
        calendar.add(day4_10);

        day5_10.setBackground(new java.awt.Color(245, 245, 246));
        day5_10.setForeground(new java.awt.Color(0, 0, 0));
        day5_10.setBorderColor(java.awt.Color.darkGray);
        day5_10.setBorderPainted(true);
        day5_10.setName("day5_10"); // NOI18N
        day5_10.setRoundBottomLeft(13);
        day5_10.setRoundBottomRight(13);
        day5_10.setRoundTopLeft(13);
        day5_10.setRoundTopRight(13);
        calendar.add(day5_10);

        day6_10.setBackground(new java.awt.Color(245, 245, 246));
        day6_10.setForeground(new java.awt.Color(0, 0, 0));
        day6_10.setBorderColor(java.awt.Color.darkGray);
        day6_10.setBorderPainted(true);
        day6_10.setName("day6_10"); // NOI18N
        day6_10.setRoundBottomLeft(13);
        day6_10.setRoundBottomRight(13);
        day6_10.setRoundTopLeft(13);
        day6_10.setRoundTopRight(13);
        calendar.add(day6_10);

        day0_11.setBackground(new java.awt.Color(245, 245, 246));
        day0_11.setForeground(new java.awt.Color(0, 0, 0));
        day0_11.setBorderColor(java.awt.Color.darkGray);
        day0_11.setBorderPainted(true);
        day0_11.setName("day0_11"); // NOI18N
        day0_11.setRoundBottomLeft(13);
        day0_11.setRoundBottomRight(13);
        day0_11.setRoundTopLeft(13);
        day0_11.setRoundTopRight(13);
        calendar.add(day0_11);

        day1_11.setBackground(new java.awt.Color(245, 245, 246));
        day1_11.setForeground(new java.awt.Color(0, 0, 0));
        day1_11.setBorderColor(java.awt.Color.darkGray);
        day1_11.setBorderPainted(true);
        day1_11.setName("day1_11"); // NOI18N
        day1_11.setRoundBottomLeft(13);
        day1_11.setRoundBottomRight(13);
        day1_11.setRoundTopLeft(13);
        day1_11.setRoundTopRight(13);
        calendar.add(day1_11);

        day2_11.setBackground(new java.awt.Color(245, 245, 246));
        day2_11.setForeground(new java.awt.Color(0, 0, 0));
        day2_11.setBorderColor(java.awt.Color.darkGray);
        day2_11.setBorderPainted(true);
        day2_11.setName("day2_11"); // NOI18N
        day2_11.setRoundBottomLeft(13);
        day2_11.setRoundBottomRight(13);
        day2_11.setRoundTopLeft(13);
        day2_11.setRoundTopRight(13);
        calendar.add(day2_11);

        day3_11.setBackground(new java.awt.Color(245, 245, 246));
        day3_11.setForeground(new java.awt.Color(0, 0, 0));
        day3_11.setBorderColor(java.awt.Color.darkGray);
        day3_11.setBorderPainted(true);
        day3_11.setName("day3_11"); // NOI18N
        day3_11.setRoundBottomLeft(13);
        day3_11.setRoundBottomRight(13);
        day3_11.setRoundTopLeft(13);
        day3_11.setRoundTopRight(13);
        calendar.add(day3_11);

        day4_11.setBackground(new java.awt.Color(245, 245, 246));
        day4_11.setForeground(new java.awt.Color(0, 0, 0));
        day4_11.setBorderColor(java.awt.Color.darkGray);
        day4_11.setBorderPainted(true);
        day4_11.setName("day4_11"); // NOI18N
        day4_11.setRoundBottomLeft(13);
        day4_11.setRoundBottomRight(13);
        day4_11.setRoundTopLeft(13);
        day4_11.setRoundTopRight(13);
        calendar.add(day4_11);

        day5_11.setBackground(new java.awt.Color(245, 245, 246));
        day5_11.setForeground(new java.awt.Color(0, 0, 0));
        day5_11.setBorderColor(java.awt.Color.darkGray);
        day5_11.setBorderPainted(true);
        day5_11.setName("day5_11"); // NOI18N
        day5_11.setRoundBottomLeft(13);
        day5_11.setRoundBottomRight(13);
        day5_11.setRoundTopLeft(13);
        day5_11.setRoundTopRight(13);
        calendar.add(day5_11);

        day6_11.setBackground(new java.awt.Color(245, 245, 246));
        day6_11.setForeground(new java.awt.Color(0, 0, 0));
        day6_11.setBorderColor(java.awt.Color.darkGray);
        day6_11.setBorderPainted(true);
        day6_11.setName("day6_11"); // NOI18N
        day6_11.setRoundBottomLeft(13);
        day6_11.setRoundBottomRight(13);
        day6_11.setRoundTopLeft(13);
        day6_11.setRoundTopRight(13);
        calendar.add(day6_11);

        day0_12.setBackground(new java.awt.Color(245, 245, 246));
        day0_12.setForeground(new java.awt.Color(0, 0, 0));
        day0_12.setBorderColor(java.awt.Color.darkGray);
        day0_12.setBorderPainted(true);
        day0_12.setName("day0_12"); // NOI18N
        day0_12.setRoundBottomLeft(13);
        day0_12.setRoundBottomRight(13);
        day0_12.setRoundTopLeft(13);
        day0_12.setRoundTopRight(13);
        calendar.add(day0_12);

        day1_12.setBackground(new java.awt.Color(245, 245, 246));
        day1_12.setForeground(new java.awt.Color(0, 0, 0));
        day1_12.setBorderColor(java.awt.Color.darkGray);
        day1_12.setBorderPainted(true);
        day1_12.setName("day1_12"); // NOI18N
        day1_12.setRoundBottomLeft(13);
        day1_12.setRoundBottomRight(13);
        day1_12.setRoundTopLeft(13);
        day1_12.setRoundTopRight(13);
        calendar.add(day1_12);

        day2_12.setBackground(new java.awt.Color(245, 245, 246));
        day2_12.setForeground(new java.awt.Color(0, 0, 0));
        day2_12.setBorderColor(java.awt.Color.darkGray);
        day2_12.setBorderPainted(true);
        day2_12.setName("day2_12"); // NOI18N
        day2_12.setRoundBottomLeft(13);
        day2_12.setRoundBottomRight(13);
        day2_12.setRoundTopLeft(13);
        day2_12.setRoundTopRight(13);
        calendar.add(day2_12);

        day3_12.setBackground(new java.awt.Color(245, 245, 246));
        day3_12.setForeground(new java.awt.Color(0, 0, 0));
        day3_12.setBorderColor(java.awt.Color.darkGray);
        day3_12.setBorderPainted(true);
        day3_12.setName("day3_12"); // NOI18N
        day3_12.setRoundBottomLeft(13);
        day3_12.setRoundBottomRight(13);
        day3_12.setRoundTopLeft(13);
        day3_12.setRoundTopRight(13);
        calendar.add(day3_12);

        day4_12.setBackground(new java.awt.Color(245, 245, 246));
        day4_12.setForeground(new java.awt.Color(0, 0, 0));
        day4_12.setBorderColor(java.awt.Color.darkGray);
        day4_12.setBorderPainted(true);
        day4_12.setName("day4_12"); // NOI18N
        day4_12.setRoundBottomLeft(13);
        day4_12.setRoundBottomRight(13);
        day4_12.setRoundTopLeft(13);
        day4_12.setRoundTopRight(13);
        calendar.add(day4_12);

        day5_12.setBackground(new java.awt.Color(245, 245, 246));
        day5_12.setForeground(new java.awt.Color(0, 0, 0));
        day5_12.setBorderColor(java.awt.Color.darkGray);
        day5_12.setBorderPainted(true);
        day5_12.setName("day5_12"); // NOI18N
        day5_12.setRoundBottomLeft(13);
        day5_12.setRoundBottomRight(13);
        day5_12.setRoundTopLeft(13);
        day5_12.setRoundTopRight(13);
        calendar.add(day5_12);

        day6_12.setBackground(new java.awt.Color(245, 245, 246));
        day6_12.setForeground(new java.awt.Color(0, 0, 0));
        day6_12.setBorderColor(java.awt.Color.darkGray);
        day6_12.setBorderPainted(true);
        day6_12.setName("day6_12"); // NOI18N
        day6_12.setRoundBottomLeft(13);
        day6_12.setRoundBottomRight(13);
        day6_12.setRoundTopLeft(13);
        day6_12.setRoundTopRight(13);
        calendar.add(day6_12);

        myReservationCalendar.add(calendar);
        calendar.setBounds(30, 100, 800, 428);
        calendar.setVisible(false);

        calendarDate.setBackground(new java.awt.Color(255, 255, 255));
        calendarDate.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                calendarDateAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        calendarDate.setLayout(new java.awt.GridLayout(1, 13, 3, 0));

        date0.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date0.setForeground(new java.awt.Color(51, 51, 51));
        date0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date0);

        date1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date1.setForeground(new java.awt.Color(51, 51, 51));
        date1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date1);

        date2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date2.setForeground(new java.awt.Color(51, 51, 51));
        date2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date2);

        date3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date3.setForeground(new java.awt.Color(51, 51, 51));
        date3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date3);

        date4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date4.setForeground(new java.awt.Color(51, 51, 51));
        date4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date4);

        date5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date5.setForeground(new java.awt.Color(51, 51, 51));
        date5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date5);

        date6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        date6.setForeground(new java.awt.Color(51, 51, 51));
        date6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        calendarDate.add(date6);

        myReservationCalendar.add(calendarDate);
        calendarDate.setBounds(30, 80, 800, 20);

        calendarTime.setBackground(new java.awt.Color(255, 255, 255));
        calendarTime.setLayout(new java.awt.GridLayout(13, 7, 0, 3));

        time0.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time0.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time0.setText("1");
        calendarTime.add(time0);

        time1.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time1.setText("2");
        calendarTime.add(time1);

        time2.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time2.setText("3");
        calendarTime.add(time2);

        time3.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time3.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time3.setText("4");
        calendarTime.add(time3);

        time4.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time4.setText("5");
        calendarTime.add(time4);

        time5.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time5.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time5.setText("6");
        calendarTime.add(time5);

        time6.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time6.setText("7");
        calendarTime.add(time6);

        time7.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time7.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time7.setText("8");
        calendarTime.add(time7);

        time8.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time8.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time8.setText("9");
        calendarTime.add(time8);

        time9.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time9.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time9.setText("10");
        calendarTime.add(time9);

        time10.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time10.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time10.setText("11");
        calendarTime.add(time10);

        time11.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time11.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time11.setText("12");
        calendarTime.add(time11);

        time12.setFont(new java.awt.Font("Helvetica Neue", 0, 12)); // NOI18N
        time12.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        time12.setText("13");
        calendarTime.add(time12);

        myReservationCalendar.add(calendarTime);
        calendarTime.setBounds(8, 100, 20, 428);

        add(myReservationCalendar);
        myReservationCalendar.setBounds(252, 6, 840, 535);
    }// </editor-fold>//GEN-END:initComponents

    private void calendarDateAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_calendarDateAncestorAdded
        java.time.LocalDate today = java.time.LocalDate.now();
        java.time.format.DateTimeFormatter formatter = java.time.format.DateTimeFormatter.ofPattern("E/yyyy-MM-dd");

        JLabel[] dateLabels = { date0, date1, date2, date3, date4, date5, date6 };

        for (int i = 0; i < dateLabels.length; i++) {
            java.time.LocalDate date = today.plusDays(i);
            dateLabels[i].setText(date.format(formatter)); // 예: "수/2025-05-01"
        }
    }//GEN-LAST:event_calendarDateAncestorAdded

    // 컨트롤러 이벤트 연결
    public void addBuildingSelectionListener(ItemListener listener) {
        buildingComboBox.addItemListener(listener);
    }

    // 필드 값 가져오기
    public String getSelectedBuilding() {
        return (String) buildingComboBox.getSelectedItem();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> buildingComboBox;
    private deu.view.custom.TextFieldRound buildingField;
    private javax.swing.JLabel buildingLabel;
    private deu.view.custom.PanelRound buildingPanel;
    private javax.swing.JPanel calendar;
    private javax.swing.JPanel calendarDate;
    private javax.swing.JPanel calendarTime;
    private javax.swing.JLabel date0;
    private javax.swing.JLabel date1;
    private javax.swing.JLabel date2;
    private javax.swing.JLabel date3;
    private javax.swing.JLabel date4;
    private javax.swing.JLabel date5;
    private javax.swing.JLabel date6;
    private deu.view.custom.ButtonRound day0_0;
    private deu.view.custom.ButtonRound day0_1;
    private deu.view.custom.ButtonRound day0_10;
    private deu.view.custom.ButtonRound day0_11;
    private deu.view.custom.ButtonRound day0_12;
    private deu.view.custom.ButtonRound day0_2;
    private deu.view.custom.ButtonRound day0_3;
    private deu.view.custom.ButtonRound day0_4;
    private deu.view.custom.ButtonRound day0_5;
    private deu.view.custom.ButtonRound day0_6;
    private deu.view.custom.ButtonRound day0_7;
    private deu.view.custom.ButtonRound day0_8;
    private deu.view.custom.ButtonRound day0_9;
    private deu.view.custom.ButtonRound day1_0;
    private deu.view.custom.ButtonRound day1_1;
    private deu.view.custom.ButtonRound day1_10;
    private deu.view.custom.ButtonRound day1_11;
    private deu.view.custom.ButtonRound day1_12;
    private deu.view.custom.ButtonRound day1_2;
    private deu.view.custom.ButtonRound day1_3;
    private deu.view.custom.ButtonRound day1_4;
    private deu.view.custom.ButtonRound day1_5;
    private deu.view.custom.ButtonRound day1_6;
    private deu.view.custom.ButtonRound day1_7;
    private deu.view.custom.ButtonRound day1_8;
    private deu.view.custom.ButtonRound day1_9;
    private deu.view.custom.ButtonRound day2_0;
    private deu.view.custom.ButtonRound day2_1;
    private deu.view.custom.ButtonRound day2_10;
    private deu.view.custom.ButtonRound day2_11;
    private deu.view.custom.ButtonRound day2_12;
    private deu.view.custom.ButtonRound day2_2;
    private deu.view.custom.ButtonRound day2_3;
    private deu.view.custom.ButtonRound day2_4;
    private deu.view.custom.ButtonRound day2_5;
    private deu.view.custom.ButtonRound day2_6;
    private deu.view.custom.ButtonRound day2_7;
    private deu.view.custom.ButtonRound day2_8;
    private deu.view.custom.ButtonRound day2_9;
    private deu.view.custom.ButtonRound day3_0;
    private deu.view.custom.ButtonRound day3_1;
    private deu.view.custom.ButtonRound day3_10;
    private deu.view.custom.ButtonRound day3_11;
    private deu.view.custom.ButtonRound day3_12;
    private deu.view.custom.ButtonRound day3_2;
    private deu.view.custom.ButtonRound day3_3;
    private deu.view.custom.ButtonRound day3_4;
    private deu.view.custom.ButtonRound day3_5;
    private deu.view.custom.ButtonRound day3_6;
    private deu.view.custom.ButtonRound day3_7;
    private deu.view.custom.ButtonRound day3_8;
    private deu.view.custom.ButtonRound day3_9;
    private deu.view.custom.ButtonRound day4_0;
    private deu.view.custom.ButtonRound day4_1;
    private deu.view.custom.ButtonRound day4_10;
    private deu.view.custom.ButtonRound day4_11;
    private deu.view.custom.ButtonRound day4_12;
    private deu.view.custom.ButtonRound day4_2;
    private deu.view.custom.ButtonRound day4_3;
    private deu.view.custom.ButtonRound day4_4;
    private deu.view.custom.ButtonRound day4_5;
    private deu.view.custom.ButtonRound day4_6;
    private deu.view.custom.ButtonRound day4_7;
    private deu.view.custom.ButtonRound day4_8;
    private deu.view.custom.ButtonRound day4_9;
    private deu.view.custom.ButtonRound day5_0;
    private deu.view.custom.ButtonRound day5_1;
    private deu.view.custom.ButtonRound day5_10;
    private deu.view.custom.ButtonRound day5_11;
    private deu.view.custom.ButtonRound day5_12;
    private deu.view.custom.ButtonRound day5_2;
    private deu.view.custom.ButtonRound day5_3;
    private deu.view.custom.ButtonRound day5_4;
    private deu.view.custom.ButtonRound day5_5;
    private deu.view.custom.ButtonRound day5_6;
    private deu.view.custom.ButtonRound day5_7;
    private deu.view.custom.ButtonRound day5_8;
    private deu.view.custom.ButtonRound day5_9;
    private deu.view.custom.ButtonRound day6_0;
    private deu.view.custom.ButtonRound day6_1;
    private deu.view.custom.ButtonRound day6_10;
    private deu.view.custom.ButtonRound day6_11;
    private deu.view.custom.ButtonRound day6_12;
    private deu.view.custom.ButtonRound day6_2;
    private deu.view.custom.ButtonRound day6_3;
    private deu.view.custom.ButtonRound day6_4;
    private deu.view.custom.ButtonRound day6_5;
    private deu.view.custom.ButtonRound day6_6;
    private deu.view.custom.ButtonRound day6_7;
    private deu.view.custom.ButtonRound day6_8;
    private deu.view.custom.ButtonRound day6_9;
    private deu.view.custom.ButtonRound deleteButton;
    private deu.view.custom.TextFieldRound descriptionField;
    private javax.swing.JLabel descriptionLabel;
    private javax.swing.JPanel floorButtonPanel;
    private javax.swing.JLabel floorDisplayField;
    private deu.view.custom.PanelRound floorDisplayPanel;
    private deu.view.custom.TextFieldRound floorField;
    private javax.swing.JLabel floorLabel;
    private deu.view.custom.PanelRound floorPanel;
    private deu.view.custom.TextFieldRound lectureRoomField;
    private javax.swing.JLabel lectureRoomLabel;
    private javax.swing.JPanel lectureRoomList;
    private deu.view.custom.PanelRound lectureRoomListPanel;
    private deu.view.custom.PanelRound myReservationCalendar;
    private deu.view.custom.PanelRound reservationInformationPanel;
    private deu.view.custom.TextFieldRound reservationTimeField;
    private javax.swing.JLabel reservationUserNumberLabel;
    private javax.swing.JLabel time0;
    private javax.swing.JLabel time1;
    private javax.swing.JLabel time10;
    private javax.swing.JLabel time11;
    private javax.swing.JLabel time12;
    private javax.swing.JLabel time2;
    private javax.swing.JLabel time3;
    private javax.swing.JLabel time4;
    private javax.swing.JLabel time5;
    private javax.swing.JLabel time6;
    private javax.swing.JLabel time7;
    private javax.swing.JLabel time8;
    private javax.swing.JLabel time9;
    private deu.view.custom.TextFieldRound titleField;
    private deu.view.custom.TextFieldRound titleField1;
    private javax.swing.JLabel titleLabel;
    private javax.swing.JLabel titleLabel1;
    private deu.view.custom.ButtonRound updateButton;
    // End of variables declaration//GEN-END:variables
}
